// Generated by tools/gen_blk_tables.py from the spec tables -- do not edit.
package blk_tables_pkg;
  function automatic logic [5:0] num4x4w(input logic [4:0] i);  // Num_4x4_Blocks_Wide[bsize]
    case (i)
      5'd0: num4x4w = 6'd1;
      5'd1: num4x4w = 6'd1;
      5'd2: num4x4w = 6'd2;
      5'd3: num4x4w = 6'd2;
      5'd4: num4x4w = 6'd2;
      5'd5: num4x4w = 6'd4;
      5'd6: num4x4w = 6'd4;
      5'd7: num4x4w = 6'd4;
      5'd8: num4x4w = 6'd8;
      5'd9: num4x4w = 6'd8;
      5'd10: num4x4w = 6'd8;
      5'd11: num4x4w = 6'd16;
      5'd12: num4x4w = 6'd16;
      5'd13: num4x4w = 6'd16;
      5'd14: num4x4w = 6'd32;
      5'd15: num4x4w = 6'd32;
      5'd16: num4x4w = 6'd1;
      5'd17: num4x4w = 6'd4;
      5'd18: num4x4w = 6'd2;
      5'd19: num4x4w = 6'd8;
      5'd20: num4x4w = 6'd4;
      5'd21: num4x4w = 6'd16;
      default: num4x4w = 6'd0;
    endcase
  endfunction
  function automatic logic [5:0] num4x4h(input logic [4:0] i);  // Num_4x4_Blocks_High[bsize]
    case (i)
      5'd0: num4x4h = 6'd1;
      5'd1: num4x4h = 6'd2;
      5'd2: num4x4h = 6'd1;
      5'd3: num4x4h = 6'd2;
      5'd4: num4x4h = 6'd4;
      5'd5: num4x4h = 6'd2;
      5'd6: num4x4h = 6'd4;
      5'd7: num4x4h = 6'd8;
      5'd8: num4x4h = 6'd4;
      5'd9: num4x4h = 6'd8;
      5'd10: num4x4h = 6'd16;
      5'd11: num4x4h = 6'd8;
      5'd12: num4x4h = 6'd16;
      5'd13: num4x4h = 6'd32;
      5'd14: num4x4h = 6'd16;
      5'd15: num4x4h = 6'd32;
      5'd16: num4x4h = 6'd4;
      5'd17: num4x4h = 6'd1;
      5'd18: num4x4h = 6'd8;
      5'd19: num4x4h = 6'd2;
      5'd20: num4x4h = 6'd16;
      5'd21: num4x4h = 6'd4;
      default: num4x4h = 6'd0;
    endcase
  endfunction
  function automatic logic [7:0] blk_w(input logic [4:0] i);  // Block_Width[bsize]
    case (i)
      5'd0: blk_w = 8'd4;
      5'd1: blk_w = 8'd4;
      5'd2: blk_w = 8'd8;
      5'd3: blk_w = 8'd8;
      5'd4: blk_w = 8'd8;
      5'd5: blk_w = 8'd16;
      5'd6: blk_w = 8'd16;
      5'd7: blk_w = 8'd16;
      5'd8: blk_w = 8'd32;
      5'd9: blk_w = 8'd32;
      5'd10: blk_w = 8'd32;
      5'd11: blk_w = 8'd64;
      5'd12: blk_w = 8'd64;
      5'd13: blk_w = 8'd64;
      5'd14: blk_w = 8'd128;
      5'd15: blk_w = 8'd128;
      5'd16: blk_w = 8'd4;
      5'd17: blk_w = 8'd16;
      5'd18: blk_w = 8'd8;
      5'd19: blk_w = 8'd32;
      5'd20: blk_w = 8'd16;
      5'd21: blk_w = 8'd64;
      default: blk_w = 8'd0;
    endcase
  endfunction
  function automatic logic [7:0] blk_h(input logic [4:0] i);  // Block_Height[bsize]
    case (i)
      5'd0: blk_h = 8'd4;
      5'd1: blk_h = 8'd8;
      5'd2: blk_h = 8'd4;
      5'd3: blk_h = 8'd8;
      5'd4: blk_h = 8'd16;
      5'd5: blk_h = 8'd8;
      5'd6: blk_h = 8'd16;
      5'd7: blk_h = 8'd32;
      5'd8: blk_h = 8'd16;
      5'd9: blk_h = 8'd32;
      5'd10: blk_h = 8'd64;
      5'd11: blk_h = 8'd32;
      5'd12: blk_h = 8'd64;
      5'd13: blk_h = 8'd128;
      5'd14: blk_h = 8'd64;
      5'd15: blk_h = 8'd128;
      5'd16: blk_h = 8'd16;
      5'd17: blk_h = 8'd4;
      5'd18: blk_h = 8'd32;
      5'd19: blk_h = 8'd8;
      5'd20: blk_h = 8'd64;
      5'd21: blk_h = 8'd16;
      default: blk_h = 8'd0;
    endcase
  endfunction
  function automatic logic [2:0] mi_w_log2(input logic [4:0] i);  // Mi_Width_Log2[bsize]
    case (i)
      5'd0: mi_w_log2 = 3'd0;
      5'd1: mi_w_log2 = 3'd0;
      5'd2: mi_w_log2 = 3'd1;
      5'd3: mi_w_log2 = 3'd1;
      5'd4: mi_w_log2 = 3'd1;
      5'd5: mi_w_log2 = 3'd2;
      5'd6: mi_w_log2 = 3'd2;
      5'd7: mi_w_log2 = 3'd2;
      5'd8: mi_w_log2 = 3'd3;
      5'd9: mi_w_log2 = 3'd3;
      5'd10: mi_w_log2 = 3'd3;
      5'd11: mi_w_log2 = 3'd4;
      5'd12: mi_w_log2 = 3'd4;
      5'd13: mi_w_log2 = 3'd4;
      5'd14: mi_w_log2 = 3'd5;
      5'd15: mi_w_log2 = 3'd5;
      5'd16: mi_w_log2 = 3'd0;
      5'd17: mi_w_log2 = 3'd2;
      5'd18: mi_w_log2 = 3'd1;
      5'd19: mi_w_log2 = 3'd3;
      5'd20: mi_w_log2 = 3'd2;
      5'd21: mi_w_log2 = 3'd4;
      default: mi_w_log2 = 3'd0;
    endcase
  endfunction
  function automatic logic [2:0] mi_h_log2(input logic [4:0] i);  // Mi_Height_Log2[bsize]
    case (i)
      5'd0: mi_h_log2 = 3'd0;
      5'd1: mi_h_log2 = 3'd1;
      5'd2: mi_h_log2 = 3'd0;
      5'd3: mi_h_log2 = 3'd1;
      5'd4: mi_h_log2 = 3'd2;
      5'd5: mi_h_log2 = 3'd1;
      5'd6: mi_h_log2 = 3'd2;
      5'd7: mi_h_log2 = 3'd3;
      5'd8: mi_h_log2 = 3'd2;
      5'd9: mi_h_log2 = 3'd3;
      5'd10: mi_h_log2 = 3'd4;
      5'd11: mi_h_log2 = 3'd3;
      5'd12: mi_h_log2 = 3'd4;
      5'd13: mi_h_log2 = 3'd5;
      5'd14: mi_h_log2 = 3'd4;
      5'd15: mi_h_log2 = 3'd5;
      5'd16: mi_h_log2 = 3'd2;
      5'd17: mi_h_log2 = 3'd0;
      5'd18: mi_h_log2 = 3'd3;
      5'd19: mi_h_log2 = 3'd1;
      5'd20: mi_h_log2 = 3'd4;
      5'd21: mi_h_log2 = 3'd2;
      default: mi_h_log2 = 3'd0;
    endcase
  endfunction
  function automatic logic [2:0] intra_mode_ctx(input logic [3:0] i);  // Intra_Mode_Context[ymode]
    case (i)
      4'd0: intra_mode_ctx = 3'd0;
      4'd1: intra_mode_ctx = 3'd1;
      4'd2: intra_mode_ctx = 3'd2;
      4'd3: intra_mode_ctx = 3'd3;
      4'd4: intra_mode_ctx = 3'd4;
      4'd5: intra_mode_ctx = 3'd4;
      4'd6: intra_mode_ctx = 3'd4;
      4'd7: intra_mode_ctx = 3'd4;
      4'd8: intra_mode_ctx = 3'd3;
      4'd9: intra_mode_ctx = 3'd0;
      4'd10: intra_mode_ctx = 3'd1;
      4'd11: intra_mode_ctx = 3'd2;
      4'd12: intra_mode_ctx = 3'd0;
      default: intra_mode_ctx = 3'd0;
    endcase
  endfunction
  function automatic logic [4:0] max_tx_size_rect(input logic [4:0] i);  // Max_Tx_Size_Rect[bsize]
    case (i)
      5'd0: max_tx_size_rect = 5'd0;
      5'd1: max_tx_size_rect = 5'd5;
      5'd2: max_tx_size_rect = 5'd6;
      5'd3: max_tx_size_rect = 5'd1;
      5'd4: max_tx_size_rect = 5'd7;
      5'd5: max_tx_size_rect = 5'd8;
      5'd6: max_tx_size_rect = 5'd2;
      5'd7: max_tx_size_rect = 5'd9;
      5'd8: max_tx_size_rect = 5'd10;
      5'd9: max_tx_size_rect = 5'd3;
      5'd10: max_tx_size_rect = 5'd11;
      5'd11: max_tx_size_rect = 5'd12;
      5'd12: max_tx_size_rect = 5'd4;
      5'd13: max_tx_size_rect = 5'd4;
      5'd14: max_tx_size_rect = 5'd4;
      5'd15: max_tx_size_rect = 5'd4;
      5'd16: max_tx_size_rect = 5'd13;
      5'd17: max_tx_size_rect = 5'd14;
      5'd18: max_tx_size_rect = 5'd15;
      5'd19: max_tx_size_rect = 5'd16;
      5'd20: max_tx_size_rect = 5'd17;
      5'd21: max_tx_size_rect = 5'd18;
      default: max_tx_size_rect = 5'd0;
    endcase
  endfunction
  function automatic logic [2:0] max_tx_depth(input logic [4:0] i);  // Max_Tx_Depth[bsize]
    case (i)
      5'd0: max_tx_depth = 3'd0;
      5'd1: max_tx_depth = 3'd1;
      5'd2: max_tx_depth = 3'd1;
      5'd3: max_tx_depth = 3'd1;
      5'd4: max_tx_depth = 3'd2;
      5'd5: max_tx_depth = 3'd2;
      5'd6: max_tx_depth = 3'd2;
      5'd7: max_tx_depth = 3'd3;
      5'd8: max_tx_depth = 3'd3;
      5'd9: max_tx_depth = 3'd3;
      5'd10: max_tx_depth = 3'd4;
      5'd11: max_tx_depth = 3'd4;
      5'd12: max_tx_depth = 3'd4;
      5'd13: max_tx_depth = 3'd4;
      5'd14: max_tx_depth = 3'd4;
      5'd15: max_tx_depth = 3'd4;
      5'd16: max_tx_depth = 3'd2;
      5'd17: max_tx_depth = 3'd2;
      5'd18: max_tx_depth = 3'd3;
      5'd19: max_tx_depth = 3'd3;
      5'd20: max_tx_depth = 3'd4;
      5'd21: max_tx_depth = 3'd4;
      default: max_tx_depth = 3'd0;
    endcase
  endfunction
  function automatic logic [4:0] split_tx_size(input logic [4:0] i);  // Split_Tx_Size[tx]
    case (i)
      5'd0: split_tx_size = 5'd0;
      5'd1: split_tx_size = 5'd0;
      5'd2: split_tx_size = 5'd1;
      5'd3: split_tx_size = 5'd2;
      5'd4: split_tx_size = 5'd3;
      5'd5: split_tx_size = 5'd0;
      5'd6: split_tx_size = 5'd0;
      5'd7: split_tx_size = 5'd1;
      5'd8: split_tx_size = 5'd1;
      5'd9: split_tx_size = 5'd2;
      5'd10: split_tx_size = 5'd2;
      5'd11: split_tx_size = 5'd3;
      5'd12: split_tx_size = 5'd3;
      5'd13: split_tx_size = 5'd5;
      5'd14: split_tx_size = 5'd6;
      5'd15: split_tx_size = 5'd7;
      5'd16: split_tx_size = 5'd8;
      5'd17: split_tx_size = 5'd9;
      5'd18: split_tx_size = 5'd10;
      default: split_tx_size = 5'd0;
    endcase
  endfunction
  function automatic logic [6:0] tx_width(input logic [4:0] i);  // Tx_Width[tx]
    case (i)
      5'd0: tx_width = 7'd4;
      5'd1: tx_width = 7'd8;
      5'd2: tx_width = 7'd16;
      5'd3: tx_width = 7'd32;
      5'd4: tx_width = 7'd64;
      5'd5: tx_width = 7'd4;
      5'd6: tx_width = 7'd8;
      5'd7: tx_width = 7'd8;
      5'd8: tx_width = 7'd16;
      5'd9: tx_width = 7'd16;
      5'd10: tx_width = 7'd32;
      5'd11: tx_width = 7'd32;
      5'd12: tx_width = 7'd64;
      5'd13: tx_width = 7'd4;
      5'd14: tx_width = 7'd16;
      5'd15: tx_width = 7'd8;
      5'd16: tx_width = 7'd32;
      5'd17: tx_width = 7'd16;
      5'd18: tx_width = 7'd64;
      default: tx_width = 7'd0;
    endcase
  endfunction
  function automatic logic [6:0] tx_height(input logic [4:0] i);  // Tx_Height[tx]
    case (i)
      5'd0: tx_height = 7'd4;
      5'd1: tx_height = 7'd8;
      5'd2: tx_height = 7'd16;
      5'd3: tx_height = 7'd32;
      5'd4: tx_height = 7'd64;
      5'd5: tx_height = 7'd8;
      5'd6: tx_height = 7'd4;
      5'd7: tx_height = 7'd16;
      5'd8: tx_height = 7'd8;
      5'd9: tx_height = 7'd32;
      5'd10: tx_height = 7'd16;
      5'd11: tx_height = 7'd64;
      5'd12: tx_height = 7'd32;
      5'd13: tx_height = 7'd16;
      5'd14: tx_height = 7'd4;
      5'd15: tx_height = 7'd32;
      5'd16: tx_height = 7'd8;
      5'd17: tx_height = 7'd64;
      5'd18: tx_height = 7'd16;
      default: tx_height = 7'd0;
    endcase
  endfunction
  function automatic logic [3:0] mode_to_txfm(input logic [3:0] i);  // Mode_To_Txfm[mode] (intra modes incl. UV_CFL)
    case (i)
      4'd0: mode_to_txfm = 4'd0;
      4'd1: mode_to_txfm = 4'd1;
      4'd2: mode_to_txfm = 4'd2;
      4'd3: mode_to_txfm = 4'd0;
      4'd4: mode_to_txfm = 4'd3;
      4'd5: mode_to_txfm = 4'd1;
      4'd6: mode_to_txfm = 4'd2;
      4'd7: mode_to_txfm = 4'd2;
      4'd8: mode_to_txfm = 4'd1;
      4'd9: mode_to_txfm = 4'd3;
      4'd10: mode_to_txfm = 4'd1;
      4'd11: mode_to_txfm = 4'd2;
      4'd12: mode_to_txfm = 4'd3;
      4'd13: mode_to_txfm = 4'd0;
      default: mode_to_txfm = 4'd0;
    endcase
  endfunction
  function automatic logic [3:0] tx_type_intra_inv_set1(input logic [2:0] i);  // Tx_Type_Intra_Inv_Set1[v]
    case (i)
      3'd0: tx_type_intra_inv_set1 = 4'd9;
      3'd1: tx_type_intra_inv_set1 = 4'd0;
      3'd2: tx_type_intra_inv_set1 = 4'd10;
      3'd3: tx_type_intra_inv_set1 = 4'd11;
      3'd4: tx_type_intra_inv_set1 = 4'd3;
      3'd5: tx_type_intra_inv_set1 = 4'd1;
      3'd6: tx_type_intra_inv_set1 = 4'd2;
      default: tx_type_intra_inv_set1 = 4'd0;
    endcase
  endfunction
  function automatic logic [3:0] tx_type_intra_inv_set2(input logic [2:0] i);  // Tx_Type_Intra_Inv_Set2[v]
    case (i)
      3'd0: tx_type_intra_inv_set2 = 4'd9;
      3'd1: tx_type_intra_inv_set2 = 4'd0;
      3'd2: tx_type_intra_inv_set2 = 4'd3;
      3'd3: tx_type_intra_inv_set2 = 4'd1;
      3'd4: tx_type_intra_inv_set2 = 4'd2;
      default: tx_type_intra_inv_set2 = 4'd0;
    endcase
  endfunction
  function automatic logic [3:0] filter_intra_mode_to_intra_dir(input logic [2:0] i);  // Filter_Intra_Mode_To_Intra_Dir[m]
    case (i)
      3'd0: filter_intra_mode_to_intra_dir = 4'd0;
      3'd1: filter_intra_mode_to_intra_dir = 4'd1;
      3'd2: filter_intra_mode_to_intra_dir = 4'd2;
      3'd3: filter_intra_mode_to_intra_dir = 4'd6;
      3'd4: filter_intra_mode_to_intra_dir = 4'd0;
      default: filter_intra_mode_to_intra_dir = 4'd0;
    endcase
  endfunction
  function automatic logic [3:0] tx_type_inter_inv_set1(input logic [3:0] i);  // Tx_Type_Inter_Inv_Set1[v]
    case (i)
      4'd0: tx_type_inter_inv_set1 = 4'd9;
      4'd1: tx_type_inter_inv_set1 = 4'd10;
      4'd2: tx_type_inter_inv_set1 = 4'd11;
      4'd3: tx_type_inter_inv_set1 = 4'd12;
      4'd4: tx_type_inter_inv_set1 = 4'd13;
      4'd5: tx_type_inter_inv_set1 = 4'd14;
      4'd6: tx_type_inter_inv_set1 = 4'd15;
      4'd7: tx_type_inter_inv_set1 = 4'd0;
      4'd8: tx_type_inter_inv_set1 = 4'd1;
      4'd9: tx_type_inter_inv_set1 = 4'd2;
      4'd10: tx_type_inter_inv_set1 = 4'd4;
      4'd11: tx_type_inter_inv_set1 = 4'd5;
      4'd12: tx_type_inter_inv_set1 = 4'd3;
      4'd13: tx_type_inter_inv_set1 = 4'd6;
      4'd14: tx_type_inter_inv_set1 = 4'd7;
      4'd15: tx_type_inter_inv_set1 = 4'd8;
      default: tx_type_inter_inv_set1 = 4'd0;
    endcase
  endfunction
  function automatic logic [3:0] tx_type_inter_inv_set2(input logic [3:0] i);  // Tx_Type_Inter_Inv_Set2[v]
    case (i)
      4'd0: tx_type_inter_inv_set2 = 4'd9;
      4'd1: tx_type_inter_inv_set2 = 4'd10;
      4'd2: tx_type_inter_inv_set2 = 4'd11;
      4'd3: tx_type_inter_inv_set2 = 4'd0;
      4'd4: tx_type_inter_inv_set2 = 4'd1;
      4'd5: tx_type_inter_inv_set2 = 4'd2;
      4'd6: tx_type_inter_inv_set2 = 4'd4;
      4'd7: tx_type_inter_inv_set2 = 4'd5;
      4'd8: tx_type_inter_inv_set2 = 4'd3;
      4'd9: tx_type_inter_inv_set2 = 4'd6;
      4'd10: tx_type_inter_inv_set2 = 4'd7;
      4'd11: tx_type_inter_inv_set2 = 4'd8;
      default: tx_type_inter_inv_set2 = 4'd0;
    endcase
  endfunction
  function automatic logic [3:0] tx_type_inter_inv_set3(input logic [0:0] i);  // Tx_Type_Inter_Inv_Set3[v]
    case (i)
      1'd0: tx_type_inter_inv_set3 = 4'd9;
      1'd1: tx_type_inter_inv_set3 = 4'd0;
      default: tx_type_inter_inv_set3 = 4'd0;
    endcase
  endfunction
  function automatic logic [4:0] sb_size_bsize(input logic [0:0] i);  // superblock block size by use_128x128
    case (i)
      1'd0: sb_size_bsize = 5'd12;
      1'd1: sb_size_bsize = 5'd15;
      default: sb_size_bsize = 5'd0;
    endcase
  endfunction
  function automatic logic [4:0] partition_subsize(input logic [3:0] p, input logic [4:0] b);  // Partition_Subsize[p][b]
    case ({p, b})
      {4'd0, 5'd0}: partition_subsize = 5'd0;
      {4'd0, 5'd1}: partition_subsize = 5'd22;
      {4'd0, 5'd2}: partition_subsize = 5'd22;
      {4'd0, 5'd3}: partition_subsize = 5'd3;
      {4'd0, 5'd4}: partition_subsize = 5'd22;
      {4'd0, 5'd5}: partition_subsize = 5'd22;
      {4'd0, 5'd6}: partition_subsize = 5'd6;
      {4'd0, 5'd7}: partition_subsize = 5'd22;
      {4'd0, 5'd8}: partition_subsize = 5'd22;
      {4'd0, 5'd9}: partition_subsize = 5'd9;
      {4'd0, 5'd10}: partition_subsize = 5'd22;
      {4'd0, 5'd11}: partition_subsize = 5'd22;
      {4'd0, 5'd12}: partition_subsize = 5'd12;
      {4'd0, 5'd13}: partition_subsize = 5'd22;
      {4'd0, 5'd14}: partition_subsize = 5'd22;
      {4'd0, 5'd15}: partition_subsize = 5'd15;
      {4'd0, 5'd16}: partition_subsize = 5'd22;
      {4'd0, 5'd17}: partition_subsize = 5'd22;
      {4'd0, 5'd18}: partition_subsize = 5'd22;
      {4'd0, 5'd19}: partition_subsize = 5'd22;
      {4'd0, 5'd20}: partition_subsize = 5'd22;
      {4'd0, 5'd21}: partition_subsize = 5'd22;
      {4'd1, 5'd0}: partition_subsize = 5'd22;
      {4'd1, 5'd1}: partition_subsize = 5'd22;
      {4'd1, 5'd2}: partition_subsize = 5'd22;
      {4'd1, 5'd3}: partition_subsize = 5'd2;
      {4'd1, 5'd4}: partition_subsize = 5'd22;
      {4'd1, 5'd5}: partition_subsize = 5'd22;
      {4'd1, 5'd6}: partition_subsize = 5'd5;
      {4'd1, 5'd7}: partition_subsize = 5'd22;
      {4'd1, 5'd8}: partition_subsize = 5'd22;
      {4'd1, 5'd9}: partition_subsize = 5'd8;
      {4'd1, 5'd10}: partition_subsize = 5'd22;
      {4'd1, 5'd11}: partition_subsize = 5'd22;
      {4'd1, 5'd12}: partition_subsize = 5'd11;
      {4'd1, 5'd13}: partition_subsize = 5'd22;
      {4'd1, 5'd14}: partition_subsize = 5'd22;
      {4'd1, 5'd15}: partition_subsize = 5'd14;
      {4'd1, 5'd16}: partition_subsize = 5'd22;
      {4'd1, 5'd17}: partition_subsize = 5'd22;
      {4'd1, 5'd18}: partition_subsize = 5'd22;
      {4'd1, 5'd19}: partition_subsize = 5'd22;
      {4'd1, 5'd20}: partition_subsize = 5'd22;
      {4'd1, 5'd21}: partition_subsize = 5'd22;
      {4'd2, 5'd0}: partition_subsize = 5'd22;
      {4'd2, 5'd1}: partition_subsize = 5'd22;
      {4'd2, 5'd2}: partition_subsize = 5'd22;
      {4'd2, 5'd3}: partition_subsize = 5'd1;
      {4'd2, 5'd4}: partition_subsize = 5'd22;
      {4'd2, 5'd5}: partition_subsize = 5'd22;
      {4'd2, 5'd6}: partition_subsize = 5'd4;
      {4'd2, 5'd7}: partition_subsize = 5'd22;
      {4'd2, 5'd8}: partition_subsize = 5'd22;
      {4'd2, 5'd9}: partition_subsize = 5'd7;
      {4'd2, 5'd10}: partition_subsize = 5'd22;
      {4'd2, 5'd11}: partition_subsize = 5'd22;
      {4'd2, 5'd12}: partition_subsize = 5'd10;
      {4'd2, 5'd13}: partition_subsize = 5'd22;
      {4'd2, 5'd14}: partition_subsize = 5'd22;
      {4'd2, 5'd15}: partition_subsize = 5'd13;
      {4'd2, 5'd16}: partition_subsize = 5'd22;
      {4'd2, 5'd17}: partition_subsize = 5'd22;
      {4'd2, 5'd18}: partition_subsize = 5'd22;
      {4'd2, 5'd19}: partition_subsize = 5'd22;
      {4'd2, 5'd20}: partition_subsize = 5'd22;
      {4'd2, 5'd21}: partition_subsize = 5'd22;
      {4'd3, 5'd0}: partition_subsize = 5'd22;
      {4'd3, 5'd1}: partition_subsize = 5'd22;
      {4'd3, 5'd2}: partition_subsize = 5'd22;
      {4'd3, 5'd3}: partition_subsize = 5'd0;
      {4'd3, 5'd4}: partition_subsize = 5'd22;
      {4'd3, 5'd5}: partition_subsize = 5'd22;
      {4'd3, 5'd6}: partition_subsize = 5'd3;
      {4'd3, 5'd7}: partition_subsize = 5'd22;
      {4'd3, 5'd8}: partition_subsize = 5'd22;
      {4'd3, 5'd9}: partition_subsize = 5'd6;
      {4'd3, 5'd10}: partition_subsize = 5'd22;
      {4'd3, 5'd11}: partition_subsize = 5'd22;
      {4'd3, 5'd12}: partition_subsize = 5'd9;
      {4'd3, 5'd13}: partition_subsize = 5'd22;
      {4'd3, 5'd14}: partition_subsize = 5'd22;
      {4'd3, 5'd15}: partition_subsize = 5'd12;
      {4'd3, 5'd16}: partition_subsize = 5'd22;
      {4'd3, 5'd17}: partition_subsize = 5'd22;
      {4'd3, 5'd18}: partition_subsize = 5'd22;
      {4'd3, 5'd19}: partition_subsize = 5'd22;
      {4'd3, 5'd20}: partition_subsize = 5'd22;
      {4'd3, 5'd21}: partition_subsize = 5'd22;
      {4'd4, 5'd0}: partition_subsize = 5'd22;
      {4'd4, 5'd1}: partition_subsize = 5'd22;
      {4'd4, 5'd2}: partition_subsize = 5'd22;
      {4'd4, 5'd3}: partition_subsize = 5'd2;
      {4'd4, 5'd4}: partition_subsize = 5'd22;
      {4'd4, 5'd5}: partition_subsize = 5'd22;
      {4'd4, 5'd6}: partition_subsize = 5'd5;
      {4'd4, 5'd7}: partition_subsize = 5'd22;
      {4'd4, 5'd8}: partition_subsize = 5'd22;
      {4'd4, 5'd9}: partition_subsize = 5'd8;
      {4'd4, 5'd10}: partition_subsize = 5'd22;
      {4'd4, 5'd11}: partition_subsize = 5'd22;
      {4'd4, 5'd12}: partition_subsize = 5'd11;
      {4'd4, 5'd13}: partition_subsize = 5'd22;
      {4'd4, 5'd14}: partition_subsize = 5'd22;
      {4'd4, 5'd15}: partition_subsize = 5'd14;
      {4'd4, 5'd16}: partition_subsize = 5'd22;
      {4'd4, 5'd17}: partition_subsize = 5'd22;
      {4'd4, 5'd18}: partition_subsize = 5'd22;
      {4'd4, 5'd19}: partition_subsize = 5'd22;
      {4'd4, 5'd20}: partition_subsize = 5'd22;
      {4'd4, 5'd21}: partition_subsize = 5'd22;
      {4'd5, 5'd0}: partition_subsize = 5'd22;
      {4'd5, 5'd1}: partition_subsize = 5'd22;
      {4'd5, 5'd2}: partition_subsize = 5'd22;
      {4'd5, 5'd3}: partition_subsize = 5'd2;
      {4'd5, 5'd4}: partition_subsize = 5'd22;
      {4'd5, 5'd5}: partition_subsize = 5'd22;
      {4'd5, 5'd6}: partition_subsize = 5'd5;
      {4'd5, 5'd7}: partition_subsize = 5'd22;
      {4'd5, 5'd8}: partition_subsize = 5'd22;
      {4'd5, 5'd9}: partition_subsize = 5'd8;
      {4'd5, 5'd10}: partition_subsize = 5'd22;
      {4'd5, 5'd11}: partition_subsize = 5'd22;
      {4'd5, 5'd12}: partition_subsize = 5'd11;
      {4'd5, 5'd13}: partition_subsize = 5'd22;
      {4'd5, 5'd14}: partition_subsize = 5'd22;
      {4'd5, 5'd15}: partition_subsize = 5'd14;
      {4'd5, 5'd16}: partition_subsize = 5'd22;
      {4'd5, 5'd17}: partition_subsize = 5'd22;
      {4'd5, 5'd18}: partition_subsize = 5'd22;
      {4'd5, 5'd19}: partition_subsize = 5'd22;
      {4'd5, 5'd20}: partition_subsize = 5'd22;
      {4'd5, 5'd21}: partition_subsize = 5'd22;
      {4'd6, 5'd0}: partition_subsize = 5'd22;
      {4'd6, 5'd1}: partition_subsize = 5'd22;
      {4'd6, 5'd2}: partition_subsize = 5'd22;
      {4'd6, 5'd3}: partition_subsize = 5'd1;
      {4'd6, 5'd4}: partition_subsize = 5'd22;
      {4'd6, 5'd5}: partition_subsize = 5'd22;
      {4'd6, 5'd6}: partition_subsize = 5'd4;
      {4'd6, 5'd7}: partition_subsize = 5'd22;
      {4'd6, 5'd8}: partition_subsize = 5'd22;
      {4'd6, 5'd9}: partition_subsize = 5'd7;
      {4'd6, 5'd10}: partition_subsize = 5'd22;
      {4'd6, 5'd11}: partition_subsize = 5'd22;
      {4'd6, 5'd12}: partition_subsize = 5'd10;
      {4'd6, 5'd13}: partition_subsize = 5'd22;
      {4'd6, 5'd14}: partition_subsize = 5'd22;
      {4'd6, 5'd15}: partition_subsize = 5'd13;
      {4'd6, 5'd16}: partition_subsize = 5'd22;
      {4'd6, 5'd17}: partition_subsize = 5'd22;
      {4'd6, 5'd18}: partition_subsize = 5'd22;
      {4'd6, 5'd19}: partition_subsize = 5'd22;
      {4'd6, 5'd20}: partition_subsize = 5'd22;
      {4'd6, 5'd21}: partition_subsize = 5'd22;
      {4'd7, 5'd0}: partition_subsize = 5'd22;
      {4'd7, 5'd1}: partition_subsize = 5'd22;
      {4'd7, 5'd2}: partition_subsize = 5'd22;
      {4'd7, 5'd3}: partition_subsize = 5'd1;
      {4'd7, 5'd4}: partition_subsize = 5'd22;
      {4'd7, 5'd5}: partition_subsize = 5'd22;
      {4'd7, 5'd6}: partition_subsize = 5'd4;
      {4'd7, 5'd7}: partition_subsize = 5'd22;
      {4'd7, 5'd8}: partition_subsize = 5'd22;
      {4'd7, 5'd9}: partition_subsize = 5'd7;
      {4'd7, 5'd10}: partition_subsize = 5'd22;
      {4'd7, 5'd11}: partition_subsize = 5'd22;
      {4'd7, 5'd12}: partition_subsize = 5'd10;
      {4'd7, 5'd13}: partition_subsize = 5'd22;
      {4'd7, 5'd14}: partition_subsize = 5'd22;
      {4'd7, 5'd15}: partition_subsize = 5'd13;
      {4'd7, 5'd16}: partition_subsize = 5'd22;
      {4'd7, 5'd17}: partition_subsize = 5'd22;
      {4'd7, 5'd18}: partition_subsize = 5'd22;
      {4'd7, 5'd19}: partition_subsize = 5'd22;
      {4'd7, 5'd20}: partition_subsize = 5'd22;
      {4'd7, 5'd21}: partition_subsize = 5'd22;
      {4'd8, 5'd0}: partition_subsize = 5'd22;
      {4'd8, 5'd1}: partition_subsize = 5'd22;
      {4'd8, 5'd2}: partition_subsize = 5'd22;
      {4'd8, 5'd3}: partition_subsize = 5'd22;
      {4'd8, 5'd4}: partition_subsize = 5'd22;
      {4'd8, 5'd5}: partition_subsize = 5'd22;
      {4'd8, 5'd6}: partition_subsize = 5'd17;
      {4'd8, 5'd7}: partition_subsize = 5'd22;
      {4'd8, 5'd8}: partition_subsize = 5'd22;
      {4'd8, 5'd9}: partition_subsize = 5'd19;
      {4'd8, 5'd10}: partition_subsize = 5'd22;
      {4'd8, 5'd11}: partition_subsize = 5'd22;
      {4'd8, 5'd12}: partition_subsize = 5'd21;
      {4'd8, 5'd13}: partition_subsize = 5'd22;
      {4'd8, 5'd14}: partition_subsize = 5'd22;
      {4'd8, 5'd15}: partition_subsize = 5'd22;
      {4'd8, 5'd16}: partition_subsize = 5'd22;
      {4'd8, 5'd17}: partition_subsize = 5'd22;
      {4'd8, 5'd18}: partition_subsize = 5'd22;
      {4'd8, 5'd19}: partition_subsize = 5'd22;
      {4'd8, 5'd20}: partition_subsize = 5'd22;
      {4'd8, 5'd21}: partition_subsize = 5'd22;
      {4'd9, 5'd0}: partition_subsize = 5'd22;
      {4'd9, 5'd1}: partition_subsize = 5'd22;
      {4'd9, 5'd2}: partition_subsize = 5'd22;
      {4'd9, 5'd3}: partition_subsize = 5'd22;
      {4'd9, 5'd4}: partition_subsize = 5'd22;
      {4'd9, 5'd5}: partition_subsize = 5'd22;
      {4'd9, 5'd6}: partition_subsize = 5'd16;
      {4'd9, 5'd7}: partition_subsize = 5'd22;
      {4'd9, 5'd8}: partition_subsize = 5'd22;
      {4'd9, 5'd9}: partition_subsize = 5'd18;
      {4'd9, 5'd10}: partition_subsize = 5'd22;
      {4'd9, 5'd11}: partition_subsize = 5'd22;
      {4'd9, 5'd12}: partition_subsize = 5'd20;
      {4'd9, 5'd13}: partition_subsize = 5'd22;
      {4'd9, 5'd14}: partition_subsize = 5'd22;
      {4'd9, 5'd15}: partition_subsize = 5'd22;
      {4'd9, 5'd16}: partition_subsize = 5'd22;
      {4'd9, 5'd17}: partition_subsize = 5'd22;
      {4'd9, 5'd18}: partition_subsize = 5'd22;
      {4'd9, 5'd19}: partition_subsize = 5'd22;
      {4'd9, 5'd20}: partition_subsize = 5'd22;
      {4'd9, 5'd21}: partition_subsize = 5'd22;
      default: partition_subsize = 5'd22;
    endcase
  endfunction
  function automatic logic [4:0] subsampled_size(input logic [4:0] b, input logic sx, input logic sy);  // Subsampled_Size[b][sx][sy]
    case ({b, sx, sy})
      {5'd0, 1'b0, 1'b0}: subsampled_size = 5'd0;
      {5'd0, 1'b0, 1'b1}: subsampled_size = 5'd0;
      {5'd0, 1'b1, 1'b0}: subsampled_size = 5'd0;
      {5'd0, 1'b1, 1'b1}: subsampled_size = 5'd0;
      {5'd1, 1'b0, 1'b0}: subsampled_size = 5'd1;
      {5'd1, 1'b0, 1'b1}: subsampled_size = 5'd0;
      {5'd1, 1'b1, 1'b0}: subsampled_size = 5'd22;
      {5'd1, 1'b1, 1'b1}: subsampled_size = 5'd0;
      {5'd2, 1'b0, 1'b0}: subsampled_size = 5'd2;
      {5'd2, 1'b0, 1'b1}: subsampled_size = 5'd22;
      {5'd2, 1'b1, 1'b0}: subsampled_size = 5'd0;
      {5'd2, 1'b1, 1'b1}: subsampled_size = 5'd0;
      {5'd3, 1'b0, 1'b0}: subsampled_size = 5'd3;
      {5'd3, 1'b0, 1'b1}: subsampled_size = 5'd2;
      {5'd3, 1'b1, 1'b0}: subsampled_size = 5'd1;
      {5'd3, 1'b1, 1'b1}: subsampled_size = 5'd0;
      {5'd4, 1'b0, 1'b0}: subsampled_size = 5'd4;
      {5'd4, 1'b0, 1'b1}: subsampled_size = 5'd3;
      {5'd4, 1'b1, 1'b0}: subsampled_size = 5'd22;
      {5'd4, 1'b1, 1'b1}: subsampled_size = 5'd1;
      {5'd5, 1'b0, 1'b0}: subsampled_size = 5'd5;
      {5'd5, 1'b0, 1'b1}: subsampled_size = 5'd22;
      {5'd5, 1'b1, 1'b0}: subsampled_size = 5'd3;
      {5'd5, 1'b1, 1'b1}: subsampled_size = 5'd2;
      {5'd6, 1'b0, 1'b0}: subsampled_size = 5'd6;
      {5'd6, 1'b0, 1'b1}: subsampled_size = 5'd5;
      {5'd6, 1'b1, 1'b0}: subsampled_size = 5'd4;
      {5'd6, 1'b1, 1'b1}: subsampled_size = 5'd3;
      {5'd7, 1'b0, 1'b0}: subsampled_size = 5'd7;
      {5'd7, 1'b0, 1'b1}: subsampled_size = 5'd6;
      {5'd7, 1'b1, 1'b0}: subsampled_size = 5'd22;
      {5'd7, 1'b1, 1'b1}: subsampled_size = 5'd4;
      {5'd8, 1'b0, 1'b0}: subsampled_size = 5'd8;
      {5'd8, 1'b0, 1'b1}: subsampled_size = 5'd22;
      {5'd8, 1'b1, 1'b0}: subsampled_size = 5'd6;
      {5'd8, 1'b1, 1'b1}: subsampled_size = 5'd5;
      {5'd9, 1'b0, 1'b0}: subsampled_size = 5'd9;
      {5'd9, 1'b0, 1'b1}: subsampled_size = 5'd8;
      {5'd9, 1'b1, 1'b0}: subsampled_size = 5'd7;
      {5'd9, 1'b1, 1'b1}: subsampled_size = 5'd6;
      {5'd10, 1'b0, 1'b0}: subsampled_size = 5'd10;
      {5'd10, 1'b0, 1'b1}: subsampled_size = 5'd9;
      {5'd10, 1'b1, 1'b0}: subsampled_size = 5'd22;
      {5'd10, 1'b1, 1'b1}: subsampled_size = 5'd7;
      {5'd11, 1'b0, 1'b0}: subsampled_size = 5'd11;
      {5'd11, 1'b0, 1'b1}: subsampled_size = 5'd22;
      {5'd11, 1'b1, 1'b0}: subsampled_size = 5'd9;
      {5'd11, 1'b1, 1'b1}: subsampled_size = 5'd8;
      {5'd12, 1'b0, 1'b0}: subsampled_size = 5'd12;
      {5'd12, 1'b0, 1'b1}: subsampled_size = 5'd11;
      {5'd12, 1'b1, 1'b0}: subsampled_size = 5'd10;
      {5'd12, 1'b1, 1'b1}: subsampled_size = 5'd9;
      {5'd13, 1'b0, 1'b0}: subsampled_size = 5'd13;
      {5'd13, 1'b0, 1'b1}: subsampled_size = 5'd12;
      {5'd13, 1'b1, 1'b0}: subsampled_size = 5'd22;
      {5'd13, 1'b1, 1'b1}: subsampled_size = 5'd10;
      {5'd14, 1'b0, 1'b0}: subsampled_size = 5'd14;
      {5'd14, 1'b0, 1'b1}: subsampled_size = 5'd22;
      {5'd14, 1'b1, 1'b0}: subsampled_size = 5'd12;
      {5'd14, 1'b1, 1'b1}: subsampled_size = 5'd11;
      {5'd15, 1'b0, 1'b0}: subsampled_size = 5'd15;
      {5'd15, 1'b0, 1'b1}: subsampled_size = 5'd14;
      {5'd15, 1'b1, 1'b0}: subsampled_size = 5'd13;
      {5'd15, 1'b1, 1'b1}: subsampled_size = 5'd12;
      {5'd16, 1'b0, 1'b0}: subsampled_size = 5'd16;
      {5'd16, 1'b0, 1'b1}: subsampled_size = 5'd1;
      {5'd16, 1'b1, 1'b0}: subsampled_size = 5'd22;
      {5'd16, 1'b1, 1'b1}: subsampled_size = 5'd1;
      {5'd17, 1'b0, 1'b0}: subsampled_size = 5'd17;
      {5'd17, 1'b0, 1'b1}: subsampled_size = 5'd22;
      {5'd17, 1'b1, 1'b0}: subsampled_size = 5'd2;
      {5'd17, 1'b1, 1'b1}: subsampled_size = 5'd2;
      {5'd18, 1'b0, 1'b0}: subsampled_size = 5'd18;
      {5'd18, 1'b0, 1'b1}: subsampled_size = 5'd4;
      {5'd18, 1'b1, 1'b0}: subsampled_size = 5'd22;
      {5'd18, 1'b1, 1'b1}: subsampled_size = 5'd16;
      {5'd19, 1'b0, 1'b0}: subsampled_size = 5'd19;
      {5'd19, 1'b0, 1'b1}: subsampled_size = 5'd22;
      {5'd19, 1'b1, 1'b0}: subsampled_size = 5'd5;
      {5'd19, 1'b1, 1'b1}: subsampled_size = 5'd17;
      {5'd20, 1'b0, 1'b0}: subsampled_size = 5'd20;
      {5'd20, 1'b0, 1'b1}: subsampled_size = 5'd7;
      {5'd20, 1'b1, 1'b0}: subsampled_size = 5'd22;
      {5'd20, 1'b1, 1'b1}: subsampled_size = 5'd18;
      {5'd21, 1'b0, 1'b0}: subsampled_size = 5'd21;
      {5'd21, 1'b0, 1'b1}: subsampled_size = 5'd22;
      {5'd21, 1'b1, 1'b0}: subsampled_size = 5'd8;
      {5'd21, 1'b1, 1'b1}: subsampled_size = 5'd19;
      default: subsampled_size = 5'd22;
    endcase
  endfunction
  function automatic logic tx_type_in_set_inter(input logic [1:0] s, input logic [3:0] t);  // Tx_Type_In_Set_Inter[s][t]
    case ({s, t})
      {2'd0, 4'd0}: tx_type_in_set_inter = 1'b1;
      {2'd0, 4'd1}: tx_type_in_set_inter = 1'b0;
      {2'd0, 4'd2}: tx_type_in_set_inter = 1'b0;
      {2'd0, 4'd3}: tx_type_in_set_inter = 1'b0;
      {2'd0, 4'd4}: tx_type_in_set_inter = 1'b0;
      {2'd0, 4'd5}: tx_type_in_set_inter = 1'b0;
      {2'd0, 4'd6}: tx_type_in_set_inter = 1'b0;
      {2'd0, 4'd7}: tx_type_in_set_inter = 1'b0;
      {2'd0, 4'd8}: tx_type_in_set_inter = 1'b0;
      {2'd0, 4'd9}: tx_type_in_set_inter = 1'b0;
      {2'd0, 4'd10}: tx_type_in_set_inter = 1'b0;
      {2'd0, 4'd11}: tx_type_in_set_inter = 1'b0;
      {2'd0, 4'd12}: tx_type_in_set_inter = 1'b0;
      {2'd0, 4'd13}: tx_type_in_set_inter = 1'b0;
      {2'd0, 4'd14}: tx_type_in_set_inter = 1'b0;
      {2'd0, 4'd15}: tx_type_in_set_inter = 1'b0;
      {2'd1, 4'd0}: tx_type_in_set_inter = 1'b1;
      {2'd1, 4'd1}: tx_type_in_set_inter = 1'b1;
      {2'd1, 4'd2}: tx_type_in_set_inter = 1'b1;
      {2'd1, 4'd3}: tx_type_in_set_inter = 1'b1;
      {2'd1, 4'd4}: tx_type_in_set_inter = 1'b1;
      {2'd1, 4'd5}: tx_type_in_set_inter = 1'b1;
      {2'd1, 4'd6}: tx_type_in_set_inter = 1'b1;
      {2'd1, 4'd7}: tx_type_in_set_inter = 1'b1;
      {2'd1, 4'd8}: tx_type_in_set_inter = 1'b1;
      {2'd1, 4'd9}: tx_type_in_set_inter = 1'b1;
      {2'd1, 4'd10}: tx_type_in_set_inter = 1'b1;
      {2'd1, 4'd11}: tx_type_in_set_inter = 1'b1;
      {2'd1, 4'd12}: tx_type_in_set_inter = 1'b1;
      {2'd1, 4'd13}: tx_type_in_set_inter = 1'b1;
      {2'd1, 4'd14}: tx_type_in_set_inter = 1'b1;
      {2'd1, 4'd15}: tx_type_in_set_inter = 1'b1;
      {2'd2, 4'd0}: tx_type_in_set_inter = 1'b1;
      {2'd2, 4'd1}: tx_type_in_set_inter = 1'b1;
      {2'd2, 4'd2}: tx_type_in_set_inter = 1'b1;
      {2'd2, 4'd3}: tx_type_in_set_inter = 1'b1;
      {2'd2, 4'd4}: tx_type_in_set_inter = 1'b1;
      {2'd2, 4'd5}: tx_type_in_set_inter = 1'b1;
      {2'd2, 4'd6}: tx_type_in_set_inter = 1'b1;
      {2'd2, 4'd7}: tx_type_in_set_inter = 1'b1;
      {2'd2, 4'd8}: tx_type_in_set_inter = 1'b1;
      {2'd2, 4'd9}: tx_type_in_set_inter = 1'b1;
      {2'd2, 4'd10}: tx_type_in_set_inter = 1'b1;
      {2'd2, 4'd11}: tx_type_in_set_inter = 1'b1;
      {2'd2, 4'd12}: tx_type_in_set_inter = 1'b0;
      {2'd2, 4'd13}: tx_type_in_set_inter = 1'b0;
      {2'd2, 4'd14}: tx_type_in_set_inter = 1'b0;
      {2'd2, 4'd15}: tx_type_in_set_inter = 1'b0;
      {2'd3, 4'd0}: tx_type_in_set_inter = 1'b1;
      {2'd3, 4'd1}: tx_type_in_set_inter = 1'b0;
      {2'd3, 4'd2}: tx_type_in_set_inter = 1'b0;
      {2'd3, 4'd3}: tx_type_in_set_inter = 1'b0;
      {2'd3, 4'd4}: tx_type_in_set_inter = 1'b0;
      {2'd3, 4'd5}: tx_type_in_set_inter = 1'b0;
      {2'd3, 4'd6}: tx_type_in_set_inter = 1'b0;
      {2'd3, 4'd7}: tx_type_in_set_inter = 1'b0;
      {2'd3, 4'd8}: tx_type_in_set_inter = 1'b0;
      {2'd3, 4'd9}: tx_type_in_set_inter = 1'b1;
      {2'd3, 4'd10}: tx_type_in_set_inter = 1'b0;
      {2'd3, 4'd11}: tx_type_in_set_inter = 1'b0;
      {2'd3, 4'd12}: tx_type_in_set_inter = 1'b0;
      {2'd3, 4'd13}: tx_type_in_set_inter = 1'b0;
      {2'd3, 4'd14}: tx_type_in_set_inter = 1'b0;
      {2'd3, 4'd15}: tx_type_in_set_inter = 1'b0;
      default: tx_type_in_set_inter = 1'b0;
    endcase
  endfunction
  function automatic logic tx_type_in_set_intra(input logic [1:0] s, input logic [3:0] t);  // Tx_Type_In_Set_Intra[s][t]
    case ({s, t})
      {2'd0, 4'd0}: tx_type_in_set_intra = 1'b1;
      {2'd0, 4'd1}: tx_type_in_set_intra = 1'b0;
      {2'd0, 4'd2}: tx_type_in_set_intra = 1'b0;
      {2'd0, 4'd3}: tx_type_in_set_intra = 1'b0;
      {2'd0, 4'd4}: tx_type_in_set_intra = 1'b0;
      {2'd0, 4'd5}: tx_type_in_set_intra = 1'b0;
      {2'd0, 4'd6}: tx_type_in_set_intra = 1'b0;
      {2'd0, 4'd7}: tx_type_in_set_intra = 1'b0;
      {2'd0, 4'd8}: tx_type_in_set_intra = 1'b0;
      {2'd0, 4'd9}: tx_type_in_set_intra = 1'b0;
      {2'd0, 4'd10}: tx_type_in_set_intra = 1'b0;
      {2'd0, 4'd11}: tx_type_in_set_intra = 1'b0;
      {2'd0, 4'd12}: tx_type_in_set_intra = 1'b0;
      {2'd0, 4'd13}: tx_type_in_set_intra = 1'b0;
      {2'd0, 4'd14}: tx_type_in_set_intra = 1'b0;
      {2'd0, 4'd15}: tx_type_in_set_intra = 1'b0;
      {2'd1, 4'd0}: tx_type_in_set_intra = 1'b1;
      {2'd1, 4'd1}: tx_type_in_set_intra = 1'b1;
      {2'd1, 4'd2}: tx_type_in_set_intra = 1'b1;
      {2'd1, 4'd3}: tx_type_in_set_intra = 1'b1;
      {2'd1, 4'd4}: tx_type_in_set_intra = 1'b0;
      {2'd1, 4'd5}: tx_type_in_set_intra = 1'b0;
      {2'd1, 4'd6}: tx_type_in_set_intra = 1'b0;
      {2'd1, 4'd7}: tx_type_in_set_intra = 1'b0;
      {2'd1, 4'd8}: tx_type_in_set_intra = 1'b0;
      {2'd1, 4'd9}: tx_type_in_set_intra = 1'b1;
      {2'd1, 4'd10}: tx_type_in_set_intra = 1'b1;
      {2'd1, 4'd11}: tx_type_in_set_intra = 1'b1;
      {2'd1, 4'd12}: tx_type_in_set_intra = 1'b0;
      {2'd1, 4'd13}: tx_type_in_set_intra = 1'b0;
      {2'd1, 4'd14}: tx_type_in_set_intra = 1'b0;
      {2'd1, 4'd15}: tx_type_in_set_intra = 1'b0;
      {2'd2, 4'd0}: tx_type_in_set_intra = 1'b1;
      {2'd2, 4'd1}: tx_type_in_set_intra = 1'b1;
      {2'd2, 4'd2}: tx_type_in_set_intra = 1'b1;
      {2'd2, 4'd3}: tx_type_in_set_intra = 1'b1;
      {2'd2, 4'd4}: tx_type_in_set_intra = 1'b0;
      {2'd2, 4'd5}: tx_type_in_set_intra = 1'b0;
      {2'd2, 4'd6}: tx_type_in_set_intra = 1'b0;
      {2'd2, 4'd7}: tx_type_in_set_intra = 1'b0;
      {2'd2, 4'd8}: tx_type_in_set_intra = 1'b0;
      {2'd2, 4'd9}: tx_type_in_set_intra = 1'b1;
      {2'd2, 4'd10}: tx_type_in_set_intra = 1'b0;
      {2'd2, 4'd11}: tx_type_in_set_intra = 1'b0;
      {2'd2, 4'd12}: tx_type_in_set_intra = 1'b0;
      {2'd2, 4'd13}: tx_type_in_set_intra = 1'b0;
      {2'd2, 4'd14}: tx_type_in_set_intra = 1'b0;
      {2'd2, 4'd15}: tx_type_in_set_intra = 1'b0;
      default: tx_type_in_set_intra = 1'b0;
    endcase
  endfunction
  localparam logic [4:0] BLOCK_INVALID = 5'd22;
endpackage
