// Generated by tools/gen_cdf_map.py from tb/cdf_map.py -- do not edit.
// One 246-bit row per CDF: [239:0] 15 x 16-bit inverted CDF entries, [245:240] adaptation counter.
package cdf_map_pkg;
  localparam int CDF_ROWS = 1167;
  localparam int CDF_COEF_ROWS = 855;   // rows [0, CDF_COEF_ROWS) depend on base_q_idx
  localparam int CDF_AW = 11;

  localparam int CDF_TXB_SKIP = 0;   // dims [5, 13] N=2
  localparam int CDF_TXB_SKIP_N = 2;
  localparam int CDF_TXB_SKIP_S0 = 13;
  localparam int CDF_TXB_SKIP_S1 = 1;
  localparam int CDF_EOB_PT_16 = 65;   // dims [2, 2] N=5
  localparam int CDF_EOB_PT_16_N = 5;
  localparam int CDF_EOB_PT_16_S0 = 2;
  localparam int CDF_EOB_PT_16_S1 = 1;
  localparam int CDF_EOB_PT_32 = 69;   // dims [2, 2] N=6
  localparam int CDF_EOB_PT_32_N = 6;
  localparam int CDF_EOB_PT_32_S0 = 2;
  localparam int CDF_EOB_PT_32_S1 = 1;
  localparam int CDF_EOB_PT_64 = 73;   // dims [2, 2] N=7
  localparam int CDF_EOB_PT_64_N = 7;
  localparam int CDF_EOB_PT_64_S0 = 2;
  localparam int CDF_EOB_PT_64_S1 = 1;
  localparam int CDF_EOB_PT_128 = 77;   // dims [2, 2] N=8
  localparam int CDF_EOB_PT_128_N = 8;
  localparam int CDF_EOB_PT_128_S0 = 2;
  localparam int CDF_EOB_PT_128_S1 = 1;
  localparam int CDF_EOB_PT_256 = 81;   // dims [2, 2] N=9
  localparam int CDF_EOB_PT_256_N = 9;
  localparam int CDF_EOB_PT_256_S0 = 2;
  localparam int CDF_EOB_PT_256_S1 = 1;
  localparam int CDF_EOB_PT_512 = 85;   // dims [2] N=10
  localparam int CDF_EOB_PT_512_N = 10;
  localparam int CDF_EOB_PT_512_S0 = 1;
  localparam int CDF_EOB_PT_1024 = 87;   // dims [2] N=11
  localparam int CDF_EOB_PT_1024_N = 11;
  localparam int CDF_EOB_PT_1024_S0 = 1;
  localparam int CDF_EOB_EXTRA = 89;   // dims [5, 2, 9] N=2
  localparam int CDF_EOB_EXTRA_N = 2;
  localparam int CDF_EOB_EXTRA_S0 = 18;
  localparam int CDF_EOB_EXTRA_S1 = 9;
  localparam int CDF_EOB_EXTRA_S2 = 1;
  localparam int CDF_DC_SIGN = 179;   // dims [2, 3] N=2
  localparam int CDF_DC_SIGN_N = 2;
  localparam int CDF_DC_SIGN_S0 = 3;
  localparam int CDF_DC_SIGN_S1 = 1;
  localparam int CDF_COEFF_BASE_EOB = 185;   // dims [5, 2, 4] N=3
  localparam int CDF_COEFF_BASE_EOB_N = 3;
  localparam int CDF_COEFF_BASE_EOB_S0 = 8;
  localparam int CDF_COEFF_BASE_EOB_S1 = 4;
  localparam int CDF_COEFF_BASE_EOB_S2 = 1;
  localparam int CDF_COEFF_BASE = 225;   // dims [5, 2, 42] N=4
  localparam int CDF_COEFF_BASE_N = 4;
  localparam int CDF_COEFF_BASE_S0 = 84;
  localparam int CDF_COEFF_BASE_S1 = 42;
  localparam int CDF_COEFF_BASE_S2 = 1;
  localparam int CDF_COEFF_BR = 645;   // dims [5, 2, 21] N=4
  localparam int CDF_COEFF_BR_N = 4;
  localparam int CDF_COEFF_BR_S0 = 42;
  localparam int CDF_COEFF_BR_S1 = 21;
  localparam int CDF_COEFF_BR_S2 = 1;
  localparam int CDF_PARTITION_W8 = 855;   // dims [4] N=4
  localparam int CDF_PARTITION_W8_N = 4;
  localparam int CDF_PARTITION_W8_S0 = 1;
  localparam int CDF_PARTITION_W16 = 859;   // dims [4] N=10
  localparam int CDF_PARTITION_W16_N = 10;
  localparam int CDF_PARTITION_W16_S0 = 1;
  localparam int CDF_PARTITION_W32 = 863;   // dims [4] N=10
  localparam int CDF_PARTITION_W32_N = 10;
  localparam int CDF_PARTITION_W32_S0 = 1;
  localparam int CDF_PARTITION_W64 = 867;   // dims [4] N=10
  localparam int CDF_PARTITION_W64_N = 10;
  localparam int CDF_PARTITION_W64_S0 = 1;
  localparam int CDF_PARTITION_W128 = 871;   // dims [4] N=8
  localparam int CDF_PARTITION_W128_N = 8;
  localparam int CDF_PARTITION_W128_S0 = 1;
  localparam int CDF_INTRABC = 875;   // dims [] N=2
  localparam int CDF_INTRABC_N = 2;
  localparam int CDF_INTRA_FRAME_Y_MODE = 876;   // dims [5, 5] N=13
  localparam int CDF_INTRA_FRAME_Y_MODE_N = 13;
  localparam int CDF_INTRA_FRAME_Y_MODE_S0 = 5;
  localparam int CDF_INTRA_FRAME_Y_MODE_S1 = 1;
  localparam int CDF_UV_MODE_CFL_ALLOWED = 901;   // dims [13] N=14
  localparam int CDF_UV_MODE_CFL_ALLOWED_N = 14;
  localparam int CDF_UV_MODE_CFL_ALLOWED_S0 = 1;
  localparam int CDF_UV_MODE_CFL_NOT_ALLOWED = 914;   // dims [13] N=13
  localparam int CDF_UV_MODE_CFL_NOT_ALLOWED_N = 13;
  localparam int CDF_UV_MODE_CFL_NOT_ALLOWED_S0 = 1;
  localparam int CDF_SEGMENT_ID = 927;   // dims [3] N=8
  localparam int CDF_SEGMENT_ID_N = 8;
  localparam int CDF_SEGMENT_ID_S0 = 1;
  localparam int CDF_SEGMENT_ID_PREDICTED = 930;   // dims [3] N=2
  localparam int CDF_SEGMENT_ID_PREDICTED_N = 2;
  localparam int CDF_SEGMENT_ID_PREDICTED_S0 = 1;
  localparam int CDF_SKIP = 933;   // dims [3] N=2
  localparam int CDF_SKIP_N = 2;
  localparam int CDF_SKIP_S0 = 1;
  localparam int CDF_DELTA_Q = 936;   // dims [] N=4
  localparam int CDF_DELTA_Q_N = 4;
  localparam int CDF_DELTA_LF = 937;   // dims [] N=4
  localparam int CDF_DELTA_LF_N = 4;
  localparam int CDF_DELTA_LF_MULTI = 938;   // dims [4] N=4
  localparam int CDF_DELTA_LF_MULTI_N = 4;
  localparam int CDF_DELTA_LF_MULTI_S0 = 1;
  localparam int CDF_ANGLE_DELTA = 942;   // dims [8] N=7
  localparam int CDF_ANGLE_DELTA_N = 7;
  localparam int CDF_ANGLE_DELTA_S0 = 1;
  localparam int CDF_CFL_SIGN = 950;   // dims [] N=8
  localparam int CDF_CFL_SIGN_N = 8;
  localparam int CDF_CFL_ALPHA = 951;   // dims [6] N=16
  localparam int CDF_CFL_ALPHA_N = 16;
  localparam int CDF_CFL_ALPHA_S0 = 1;
  localparam int CDF_PALETTE_Y_MODE = 957;   // dims [7, 3] N=2
  localparam int CDF_PALETTE_Y_MODE_N = 2;
  localparam int CDF_PALETTE_Y_MODE_S0 = 3;
  localparam int CDF_PALETTE_Y_MODE_S1 = 1;
  localparam int CDF_PALETTE_Y_SIZE = 978;   // dims [7] N=7
  localparam int CDF_PALETTE_Y_SIZE_N = 7;
  localparam int CDF_PALETTE_Y_SIZE_S0 = 1;
  localparam int CDF_PALETTE_UV_MODE = 985;   // dims [2] N=2
  localparam int CDF_PALETTE_UV_MODE_N = 2;
  localparam int CDF_PALETTE_UV_MODE_S0 = 1;
  localparam int CDF_PALETTE_UV_SIZE = 987;   // dims [7] N=7
  localparam int CDF_PALETTE_UV_SIZE_N = 7;
  localparam int CDF_PALETTE_UV_SIZE_S0 = 1;
  localparam int CDF_PALETTE_SIZE_2_Y_COLOR = 994;   // dims [5] N=2
  localparam int CDF_PALETTE_SIZE_2_Y_COLOR_N = 2;
  localparam int CDF_PALETTE_SIZE_2_Y_COLOR_S0 = 1;
  localparam int CDF_PALETTE_SIZE_2_UV_COLOR = 999;   // dims [5] N=2
  localparam int CDF_PALETTE_SIZE_2_UV_COLOR_N = 2;
  localparam int CDF_PALETTE_SIZE_2_UV_COLOR_S0 = 1;
  localparam int CDF_PALETTE_SIZE_3_Y_COLOR = 1004;   // dims [5] N=3
  localparam int CDF_PALETTE_SIZE_3_Y_COLOR_N = 3;
  localparam int CDF_PALETTE_SIZE_3_Y_COLOR_S0 = 1;
  localparam int CDF_PALETTE_SIZE_3_UV_COLOR = 1009;   // dims [5] N=3
  localparam int CDF_PALETTE_SIZE_3_UV_COLOR_N = 3;
  localparam int CDF_PALETTE_SIZE_3_UV_COLOR_S0 = 1;
  localparam int CDF_PALETTE_SIZE_4_Y_COLOR = 1014;   // dims [5] N=4
  localparam int CDF_PALETTE_SIZE_4_Y_COLOR_N = 4;
  localparam int CDF_PALETTE_SIZE_4_Y_COLOR_S0 = 1;
  localparam int CDF_PALETTE_SIZE_4_UV_COLOR = 1019;   // dims [5] N=4
  localparam int CDF_PALETTE_SIZE_4_UV_COLOR_N = 4;
  localparam int CDF_PALETTE_SIZE_4_UV_COLOR_S0 = 1;
  localparam int CDF_PALETTE_SIZE_5_Y_COLOR = 1024;   // dims [5] N=5
  localparam int CDF_PALETTE_SIZE_5_Y_COLOR_N = 5;
  localparam int CDF_PALETTE_SIZE_5_Y_COLOR_S0 = 1;
  localparam int CDF_PALETTE_SIZE_5_UV_COLOR = 1029;   // dims [5] N=5
  localparam int CDF_PALETTE_SIZE_5_UV_COLOR_N = 5;
  localparam int CDF_PALETTE_SIZE_5_UV_COLOR_S0 = 1;
  localparam int CDF_PALETTE_SIZE_6_Y_COLOR = 1034;   // dims [5] N=6
  localparam int CDF_PALETTE_SIZE_6_Y_COLOR_N = 6;
  localparam int CDF_PALETTE_SIZE_6_Y_COLOR_S0 = 1;
  localparam int CDF_PALETTE_SIZE_6_UV_COLOR = 1039;   // dims [5] N=6
  localparam int CDF_PALETTE_SIZE_6_UV_COLOR_N = 6;
  localparam int CDF_PALETTE_SIZE_6_UV_COLOR_S0 = 1;
  localparam int CDF_PALETTE_SIZE_7_Y_COLOR = 1044;   // dims [5] N=7
  localparam int CDF_PALETTE_SIZE_7_Y_COLOR_N = 7;
  localparam int CDF_PALETTE_SIZE_7_Y_COLOR_S0 = 1;
  localparam int CDF_PALETTE_SIZE_7_UV_COLOR = 1049;   // dims [5] N=7
  localparam int CDF_PALETTE_SIZE_7_UV_COLOR_N = 7;
  localparam int CDF_PALETTE_SIZE_7_UV_COLOR_S0 = 1;
  localparam int CDF_PALETTE_SIZE_8_Y_COLOR = 1054;   // dims [5] N=8
  localparam int CDF_PALETTE_SIZE_8_Y_COLOR_N = 8;
  localparam int CDF_PALETTE_SIZE_8_Y_COLOR_S0 = 1;
  localparam int CDF_PALETTE_SIZE_8_UV_COLOR = 1059;   // dims [5] N=8
  localparam int CDF_PALETTE_SIZE_8_UV_COLOR_N = 8;
  localparam int CDF_PALETTE_SIZE_8_UV_COLOR_S0 = 1;
  localparam int CDF_FILTER_INTRA = 1064;   // dims [22] N=2
  localparam int CDF_FILTER_INTRA_N = 2;
  localparam int CDF_FILTER_INTRA_S0 = 1;
  localparam int CDF_FILTER_INTRA_MODE = 1086;   // dims [] N=5
  localparam int CDF_FILTER_INTRA_MODE_N = 5;
  localparam int CDF_TX_8X8 = 1087;   // dims [3] N=2
  localparam int CDF_TX_8X8_N = 2;
  localparam int CDF_TX_8X8_S0 = 1;
  localparam int CDF_TX_16X16 = 1090;   // dims [3] N=3
  localparam int CDF_TX_16X16_N = 3;
  localparam int CDF_TX_16X16_S0 = 1;
  localparam int CDF_TX_32X32 = 1093;   // dims [3] N=3
  localparam int CDF_TX_32X32_N = 3;
  localparam int CDF_TX_32X32_S0 = 1;
  localparam int CDF_TX_64X64 = 1096;   // dims [3] N=3
  localparam int CDF_TX_64X64_N = 3;
  localparam int CDF_TX_64X64_S0 = 1;
  localparam int CDF_INTRA_TX_TYPE_SET1 = 1099;   // dims [2, 13] N=7
  localparam int CDF_INTRA_TX_TYPE_SET1_N = 7;
  localparam int CDF_INTRA_TX_TYPE_SET1_S0 = 13;
  localparam int CDF_INTRA_TX_TYPE_SET1_S1 = 1;
  localparam int CDF_INTRA_TX_TYPE_SET2 = 1125;   // dims [3, 13] N=5
  localparam int CDF_INTRA_TX_TYPE_SET2_N = 5;
  localparam int CDF_INTRA_TX_TYPE_SET2_S0 = 13;
  localparam int CDF_INTRA_TX_TYPE_SET2_S1 = 1;
  localparam int CDF_USE_WIENER = 1164;   // dims [] N=2
  localparam int CDF_USE_WIENER_N = 2;
  localparam int CDF_USE_SGRPROJ = 1165;   // dims [] N=2
  localparam int CDF_USE_SGRPROJ_N = 2;
  localparam int CDF_RESTORATION_TYPE = 1166;   // dims [] N=3
  localparam int CDF_RESTORATION_TYPE_N = 3;
endpackage
