// Generated by tools/gen_itx_ucode.py — do not edit. NSLOTS=4
// Row: kind[3:0] | slot0..slot3 each {op[1:0], a[5:0], b[5:0], angle[7:0], flip}
// Row kinds: 0 nop, 1 ops, 2 perm_dct, 3 perm_adst_in, 4 perm_adst_out, 5 adst4, 6 identity, 7 wht, 8 end
// Programs (start row by id): DCT n=2..6 -> 0..4, ADST n=2..4 -> 5..7, IDTX n=2..5 -> 8..11, WHT -> 12
/* verilator lint_off DECLFILENAME */
/* verilator lint_off UNUSEDPARAM */
package itx_ucode_pkg;
  localparam int ITX_NSLOTS = 4;
  localparam int ITX_ROWS = 151;
  localparam int ITX_ROW_W = 96;
endpackage

// program id -> first ROM row
module itx_prog_start (input logic [3:0] pid, output logic [7:0] addr);
  always_comb begin
    case (pid)
      4'd0: addr = 8'd0;
      4'd1: addr = 8'd4;
      4'd2: addr = 8'd10;
      4'd3: addr = 8'd23;
      4'd4: addr = 8'd51;
      4'd5: addr = 8'd115;
      4'd6: addr = 8'd117;
      4'd7: addr = 8'd125;
      4'd8: addr = 8'd141;
      4'd9: addr = 8'd143;
      4'd10: addr = 8'd145;
      4'd11: addr = 8'd147;
      4'd12: addr = 8'd149;
      default: addr = 8'd149;
    endcase
  end
endmodule

module itx_ucode_rom (input logic [7:0] addr, output logic [95:0] row);
  always_comb begin
    case (addr)
      8'd0: row = 96'h2; // pid 0 (n=2 cls=0) perm_dct
      8'd1: row = 96'h1083302002411; // pid 0 (n=2 cls=0) ops x2
      8'd2: row = 96'h2042004006001; // pid 0 (n=2 cls=0) ops x2
      8'd3: row = 96'h8; // pid 0 (n=2 cls=0) end
      8'd4: row = 96'h2; // pid 1 (n=3 cls=0) perm_dct
      8'd5: row = 96'h420cc080090514618220e701; // pid 1 (n=3 cls=0) ops x4
      8'd6: row = 96'h81080100180218700c20a001; // pid 1 (n=3 cls=0) ops x4
      8'd7: row = 96'h200700230a411; // pid 1 (n=3 cls=0) ops x2
      8'd8: row = 96'h106200208500408c001; // pid 1 (n=3 cls=0) ops x3
      8'd9: row = 96'h8; // pid 1 (n=3 cls=0) end
      8'd10: row = 96'h2; // pid 2 (n=4 cls=0) perm_dct
      8'd11: row = 96'h4b303094696124e1c241e781; // pid 2 (n=4 cls=0) ops x4
      8'd12: row = 96'h114618220e701; // pid 2 (n=4 cls=0) ops x2
      8'd13: row = 96'h8e3c0318680228b00c412001; // pid 2 (n=4 cls=0) ops x4
      8'd14: row = 96'h861c03082801083302002411; // pid 2 (n=4 cls=0) ops x4
      8'd15: row = 96'h81080100180134a70a712611; // pid 2 (n=4 cls=0) ops x4
      8'd16: row = 96'h220b00230a411; // pid 2 (n=4 cls=0) ops x2
      8'd17: row = 96'h801c011a700630f00c494001; // pid 2 (n=4 cls=0) ops x4
      8'd18: row = 96'h106200208500408c001; // pid 2 (n=4 cls=0) ops x3
      8'd19: row = 96'h81380100780130b20a694411; // pid 2 (n=4 cls=0) ops x4
      8'd20: row = 96'h8528010858020cc00411a001; // pid 2 (n=4 cls=0) ops x4
      8'd21: row = 96'h21c8004312001; // pid 2 (n=4 cls=0) ops x2
      8'd22: row = 96'h8; // pid 2 (n=4 cls=0) end
      8'd23: row = 96'h2; // pid 3 (n=5 cls=0) perm_dct
      8'd24: row = 96'h537038a4e97145e1e283e7c1; // pid 3 (n=5 cls=0) ops x4
      8'd25: row = 96'h576018acc93155a162a366c1; // pid 3 (n=5 cls=0) ops x4
      8'd26: row = 96'h4b303094696124e1c241e781; // pid 3 (n=5 cls=0) ops x4
      8'd27: row = 96'h965c0328a80249300c822001; // pid 3 (n=5 cls=0) ops x4
      8'd28: row = 96'h9e7c0338e80269b00cc32001; // pid 3 (n=5 cls=0) ops x4
      8'd29: row = 96'h8a2c0310480114618220e701; // pid 3 (n=5 cls=0) ops x4
      8'd30: row = 96'h238f00c61a001; // pid 3 (n=5 cls=0) ops x2
      8'd31: row = 96'h595962b4a8c575278af22711; // pid 3 (n=5 cls=0) ops x4
      8'd32: row = 96'h861c03082801083302002411; // pid 3 (n=5 cls=0) ops x4
      8'd33: row = 96'h120980134a70a712611; // pid 3 (n=5 cls=0) ops x3
      8'd34: row = 96'h986c012ab00651700c8a4001; // pid 3 (n=5 cls=0) ops x4
      8'd35: row = 96'h800c013af00671f00ccb4001; // pid 3 (n=5 cls=0) ops x4
      8'd36: row = 96'h89280110580118520c084001; // pid 3 (n=5 cls=0) ops x4
      8'd37: row = 96'h234e00c61e011; // pid 3 (n=5 cls=0) ops x2
      8'd38: row = 96'h5a55c2b6a38571330aea4611; // pid 3 (n=5 cls=0) ops x4
      8'd39: row = 96'h83100104280204600400e001; // pid 3 (n=5 cls=0) ops x4
      8'd40: row = 96'h91580120b80130b20a694411; // pid 3 (n=5 cls=0) ops x4
      8'd41: row = 96'h99780330f8064d400492a001; // pid 3 (n=5 cls=0) ops x4
      8'd42: row = 96'h8138010078026dc00cd3a011; // pid 3 (n=5 cls=0) ops x4
      8'd43: row = 96'h8528010858020cc00411a001; // pid 3 (n=5 cls=0) ops x4
      8'd44: row = 96'h21c8004312001; // pid 3 (n=5 cls=0) ops x2
      8'd45: row = 96'h585c82b2b10569520ada8411; // pid 3 (n=5 cls=0) ops x4
      8'd46: row = 96'h83700104e80205e00403e001; // pid 3 (n=5 cls=0) ops x4
      8'd47: row = 96'h8760010cc80215a004236001; // pid 3 (n=5 cls=0) ops x4
      8'd48: row = 96'h8b500114a80225600442e001; // pid 3 (n=5 cls=0) ops x4
      8'd49: row = 96'h8f40011c8802352004626001; // pid 3 (n=5 cls=0) ops x4
      8'd50: row = 96'h8; // pid 3 (n=5 cls=0) end
      8'd51: row = 96'h2; // pid 4 (n=6 cls=0) perm_dct
      8'd52: row = 96'h63f03cc5e97987e1f307e7e1; // pid 4 (n=6 cls=0) ops x4
      8'd53: row = 96'h67e01ccdc93997a1732766e1; // pid 4 (n=6 cls=0) ops x4
      8'd54: row = 96'h6bd02cd5a959a761b346e761; // pid 4 (n=6 cls=0) ops x4
      8'd55: row = 96'h6fc00cdd8919b72133666661; // pid 4 (n=6 cls=0) ops x4
      8'd56: row = 96'h537038a4e97145e1e283e7c1; // pid 4 (n=6 cls=0) ops x4
      8'd57: row = 96'h576018acc93155a162a366c1; // pid 4 (n=6 cls=0) ops x4
      8'd58: row = 96'ha69c034928028a300d042001; // pid 4 (n=6 cls=0) ops x4
      8'd59: row = 96'haebc03596802aab00d452001; // pid 4 (n=6 cls=0) ops x4
      8'd60: row = 96'hb6dc0369a802cb300d862001; // pid 4 (n=6 cls=0) ops x4
      8'd61: row = 96'hbefc0379e802ebb00dc72001; // pid 4 (n=6 cls=0) ops x4
      8'd62: row = 96'h4b303094696124e1c241e781; // pid 4 (n=6 cls=0) ops x4
      8'd63: row = 96'h965c0328a80249300c822001; // pid 4 (n=6 cls=0) ops x4
      8'd64: row = 96'h9e7c0338e80269b00cc32001; // pid 4 (n=6 cls=0) ops x4
      8'd65: row = 96'h799972f528e5f627cbf42791; // pid 4 (n=6 cls=0) ops x4
      8'd66: row = 96'h71b932e56865d6a6cbb52591; // pid 4 (n=6 cls=0) ops x4
      8'd67: row = 96'h8a2c0310480114618220e701; // pid 4 (n=6 cls=0) ops x4
      8'd68: row = 96'h5d49e2bc89c638f00c61a001; // pid 4 (n=6 cls=0) ops x4
      8'd69: row = 96'h141180165658ad2a311; // pid 4 (n=6 cls=0) ops x3
      8'd70: row = 96'ha8ac014b300692700d0c4001; // pid 4 (n=6 cls=0) ops x4
      8'd71: row = 96'hb0cc015b7006b2f00d4d4001; // pid 4 (n=6 cls=0) ops x4
      8'd72: row = 96'hb8ec016bb006d3700d8e4001; // pid 4 (n=6 cls=0) ops x4
      8'd73: row = 96'h4004837bf006f3f00dcf4001; // pid 4 (n=6 cls=0) ops x4
      8'd74: row = 96'h4e24c30c3806105002106601; // pid 4 (n=6 cls=0) ops x4
      8'd75: row = 96'h945c03229002413002694e11; // pid 4 (n=6 cls=0) ops x4
      8'd76: row = 96'h9c7c0332d00261b004aac011; // pid 4 (n=6 cls=0) ops x4
      8'd77: row = 96'h4ebc011; // pid 4 (n=6 cls=0) ops x1
      8'd78: row = 96'h7a95e2f723c5f2338bec4711; // pid 4 (n=6 cls=0) ops x4
      8'd79: row = 96'h72b562e762c5d2b18bad4311; // pid 4 (n=6 cls=0) ops x4
      8'd80: row = 96'h882c008c2906042004006001; // pid 4 (n=6 cls=0) ops x4
      8'd81: row = 96'h5d48c31a700630f00c494001; // pid 4 (n=6 cls=0) ops x4
      8'd82: row = 96'ha09c00b4ab856d470ae26611; // pid 4 (n=6 cls=0) ops x4
      8'd83: row = 96'h50cc001; // pid 4 (n=6 cls=0) ops x1
      8'd84: row = 96'ha9b8035178068e400514a001; // pid 4 (n=6 cls=0) ops x4
      8'd85: row = 96'hb1d80161b802aec00d55a011; // pid 4 (n=6 cls=0) ops x4
      8'd86: row = 96'hb9f80371f806cf400596a001; // pid 4 (n=6 cls=0) ops x4
      8'd87: row = 96'h811801003802efc00dd7a011; // pid 4 (n=6 cls=0) ops x4
      8'd88: row = 96'h4c2c829a51060c400410a001; // pid 4 (n=6 cls=0) ops x4
      8'd89: row = 96'h93500124a80245600482e001; // pid 4 (n=6 cls=0) ops x4
      8'd90: row = 96'h9b700334e80665e00cc3e011; // pid 4 (n=6 cls=0) ops x4
      8'd91: row = 96'h789cc2f33185ea530bdc8611; // pid 4 (n=6 cls=0) ops x4
      8'd92: row = 96'h74adc2eb5385da970bbd0e11; // pid 4 (n=6 cls=0) ops x4
      8'd93: row = 96'h83300104680204e00401e001; // pid 4 (n=6 cls=0) ops x4
      8'd94: row = 96'h8720010c480214a004216001; // pid 4 (n=6 cls=0) ops x4
      8'd95: row = 96'h585c82b2b10569520ada8411; // pid 4 (n=6 cls=0) ops x4
      8'd96: row = 96'hb1f803437002c3f00d05e001; // pid 4 (n=6 cls=0) ops x4
      8'd97: row = 96'hb3f003476002cbd00d15a001; // pid 4 (n=6 cls=0) ops x4
      8'd98: row = 96'hb5e8034b5002d3b00d256001; // pid 4 (n=6 cls=0) ops x4
      8'd99: row = 96'hb7e0034f4002db900d352001; // pid 4 (n=6 cls=0) ops x4
      8'd100: row = 96'h83700104e80205e00403e001; // pid 4 (n=6 cls=0) ops x4
      8'd101: row = 96'h8760010cc80215a004236001; // pid 4 (n=6 cls=0) ops x4
      8'd102: row = 96'h8b500114a80225600442e001; // pid 4 (n=6 cls=0) ops x4
      8'd103: row = 96'h8f40011c8802352004626001; // pid 4 (n=6 cls=0) ops x4
      8'd104: row = 96'h74ac82eb5105da920bbd0411; // pid 4 (n=6 cls=0) ops x4
      8'd105: row = 96'h70bc82e37105cad20b9d8411; // pid 4 (n=6 cls=0) ops x4
      8'd106: row = 96'h83f00105e80207e00407e001; // pid 4 (n=6 cls=0) ops x4
      8'd107: row = 96'h87e0010dc80217a004276001; // pid 4 (n=6 cls=0) ops x4
      8'd108: row = 96'h8bd00115a80227600446e001; // pid 4 (n=6 cls=0) ops x4
      8'd109: row = 96'h8fc0011d8802372004666001; // pid 4 (n=6 cls=0) ops x4
      8'd110: row = 96'h93b00125680246e00485e001; // pid 4 (n=6 cls=0) ops x4
      8'd111: row = 96'h97a0012d480256a004a56001; // pid 4 (n=6 cls=0) ops x4
      8'd112: row = 96'h9b9001352802666004c4e001; // pid 4 (n=6 cls=0) ops x4
      8'd113: row = 96'h9f80013d0802762004e46001; // pid 4 (n=6 cls=0) ops x4
      8'd114: row = 96'h8; // pid 4 (n=6 cls=0) end
      8'd115: row = 96'h5; // pid 5 (n=2 cls=1) adst4
      8'd116: row = 96'h8; // pid 5 (n=2 cls=1) end
      8'd117: row = 96'h3; // pid 6 (n=3 cls=1) perm_adst_in
      8'd118: row = 96'h461c328828e50832ca002791; // pid 6 (n=3 cls=1) ops x4
      8'd119: row = 96'h831c01043002045004008001; // pid 6 (n=3 cls=1) ops x4
      8'd120: row = 96'h10010011c610a20a611; // pid 6 (n=3 cls=1) ops x3
      8'd121: row = 96'h10a380204300420c001; // pid 6 (n=3 cls=1) ops x3
      8'd122: row = 96'h118720a106411; // pid 6 (n=3 cls=1) ops x2
      8'd123: row = 96'h4; // pid 6 (n=3 cls=1) perm_adst_out
      8'd124: row = 96'h8; // pid 6 (n=3 cls=1) end
      8'd125: row = 96'h3; // pid 7 (n=4 cls=1) perm_adst_in
      8'd126: row = 96'h461c9a88297508336a0027d1; // pid 7 (n=4 cls=1) ops x4
      8'd127: row = 96'h4e3c1a98687528b16a4123d1; // pid 7 (n=4 cls=1) ops x4
      8'd128: row = 96'h832c01045002049004010001; // pid 7 (n=4 cls=1) ops x4
      8'd129: row = 96'h873c010c700214d004218001; // pid 7 (n=4 cls=1) ops x4
      8'd130: row = 96'h4f38a29458c534c08a412711; // pid 7 (n=4 cls=1) ops x4
      8'd131: row = 96'h4008001; // pid 7 (n=4 cls=1) ops x1
      8'd132: row = 96'h821801126802045004418001; // pid 7 (n=4 cls=1) ops x4
      8'd133: row = 96'h11678020c700451c001; // pid 7 (n=4 cls=1) ops x3
      8'd134: row = 96'h4f38428e308530d30a20a611; // pid 7 (n=4 cls=1) ops x4
      8'd135: row = 96'h4004001; // pid 7 (n=4 cls=1) ops x1
      8'd136: row = 96'h810c0118700220a00420c001; // pid 7 (n=4 cls=1) ops x4
      8'd137: row = 96'h11a780224b00428e001; // pid 7 (n=4 cls=1) ops x3
      8'd138: row = 96'h4e3c8294590518720a106411; // pid 7 (n=4 cls=1) ops x4
      8'd139: row = 96'h4; // pid 7 (n=4 cls=1) perm_adst_out
      8'd140: row = 96'h8; // pid 7 (n=4 cls=1) end
      8'd141: row = 96'h6; // pid 8 (n=2 cls=2) identity
      8'd142: row = 96'h8; // pid 8 (n=2 cls=2) end
      8'd143: row = 96'h6; // pid 9 (n=3 cls=2) identity
      8'd144: row = 96'h8; // pid 9 (n=3 cls=2) end
      8'd145: row = 96'h6; // pid 10 (n=4 cls=2) identity
      8'd146: row = 96'h8; // pid 10 (n=4 cls=2) end
      8'd147: row = 96'h6; // pid 11 (n=5 cls=2) identity
      8'd148: row = 96'h8; // pid 11 (n=5 cls=2) end
      8'd149: row = 96'h7; // pid 12 (n=2 cls=3) wht
      8'd150: row = 96'h8; // pid 12 (n=2 cls=3) end
      default: row = '0;
    endcase
  end
endmodule
