// Quantizer_Matrix ROM (spec 7.12.3): 15 levels x 2 planes x 3344 entries, 8 bits each, loaded from
// rtl/qm_rom.hex (generated by tools/gen_q_tables.py). Registered read, 1-cycle latency.
module qm_rom #(
    parameter string HEX = "../../rtl/qm_rom.hex"       // relative to the simulation run directory (build/<top>/)
) (
    input  logic        clk,
    input  logic [16:0] addr,                             // level * 6688 + plane * 3344 + Qm_Offset[txSz] + i * tw + j
    output logic [7:0]  data
);
    logic [7:0] mem [0:100319];
    initial $readmemh(HEX, mem);
    always_ff @(posedge clk) data <= mem[addr];
endmodule
