#!/usr/bin/env python3
"""Plan a model-free Argon batch: every intra-only stream of a set (tools/argon_index.py census), grouped by the
frame-buffer size the RTL must be built with (FBX/FBY = log2 of the upscaled width / height, at least 10 x 9),
skipping streams above --max-pixels. Writes <out>/<class>.txt lists and <out>/run.sh, which makes the dav1d
reference pictures (no film grain: the Argon md5_no_film_grain semantics) and runs tb/runner.py dec_top per class.
Usage: tools/argon_batch.py <argon-set-dir> <out-dir> [--max-pixels N] [--skip file-with-stems]
"""
import csv
import io
import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
args = [a for a in sys.argv[1:] if not a.startswith("--")]
set_dir, out = Path(args[0]), Path(args[1])
max_px = int(sys.argv[sys.argv.index("--max-pixels") + 1]) if "--max-pixels" in sys.argv else 4_500_000
skip = set()
if "--skip" in sys.argv:
    skip = set(Path(sys.argv[sys.argv.index("--skip") + 1]).read_text().split())
idx = subprocess.run([sys.executable, str(ROOT / "tools" / "argon_index.py"), str(set_dir)], capture_output=True, text=True, check=True).stdout
rows = list(csv.DictReader(io.StringIO(idx)))
classes = {}
skipped = []
for r in rows:
    if r["intra_only_stream"] != "1":
        continue
    stem = Path(r["path"]).stem
    if stem in skip:
        continue
    w, h = int(r["max_w"]), int(r["max_h"])
    if w * h > max_px:
        skipped.append((stem, w, h))
        continue
    fbx = max(10, (w + 8 - 1).bit_length())      # +8: reconstruction overhang past the last 4x4 column
    fby = max(9, (h + 8 - 1).bit_length())
    classes.setdefault((fbx, fby), []).append(r["path"])
out.mkdir(parents=True, exist_ok=True)
lines = ["#!/usr/bin/env bash", "# generated by tools/argon_batch.py", "cd \"$(dirname \"$0\")/../..\" && source env.sh", "mkdir -p refout"]
lines.append("for f in $(cat " + " ".join(str(out / f"fb{x}x{y}.txt") for (x, y) in sorted(classes)) + "); do")
lines.append("  s=$(basename $f .obu); [ -f refout/$s.yuv ] || prefix-trace/bin/dav1d -q -i $f -o refout/$s.yuv --muxer yuv --threads 1 --filmgrain 0; done")
for (x, y), paths in sorted(classes.items(), key=lambda kv: (kv[0][0] * kv[0][1], kv[0])):
    name = f"fb{x}x{y}"
    (out / f"{name}.txt").write_text("\n".join(paths) + "\n")
    lines.append(f"SIM_FAST=1 FBX={x} FBY={y} TS_NOMODEL=1 TS_IVF=$(paste -sd, {out / name}.txt) python tb/runner.py dec_top > {out}/{name}.out 2>&1")
    lines.append(f"echo \"{name}: $(grep -c 'identical to dav1d' {out}/{name}.out) identical frames; $(grep -o 'AssertionError: [0-9]* / [0-9]* streams failed' {out}/{name}.out | tail -1)\" >> {out}/summary.txt")
lines.append(f"echo BATCH_DONE $(date -Is) >> {out}/summary.txt")
(out / "run.sh").write_text("\n".join(lines) + "\n")
os.chmod(out / "run.sh", 0o755)
for (x, y), paths in sorted(classes.items()):
    print(f"fb{x}x{y}: {len(paths)} streams")
print(f"skipped (> {max_px} px): {skipped}")
print(f"wrote {out}/run.sh")
