#!/usr/bin/env python3
"""Extract every constant and every table of the AV1 spec text into tb/av1_tables.py.

Constants come from the "Symbols and abbreviated terms" section (NAME / value / description triplets).
Tables are every `Name[ dims ] = { ... }` definition; the flat integer list is reshaped to the dims, which
are evaluated with the constants, so a count mismatch is detected here rather than in a decoder.

Usage: tools/gen_spec_tables.py third_party/spec/av1-spec.txt > tb/av1_tables.py
"""
import re
import sys

text = open(sys.argv[1], encoding="utf-8").read()
lines = text.split("\n")

# ---- constants -------------------------------------------------------------------------------
consts = {}
i = 0
while i < len(lines) - 1:
    a = lines[i].strip()
    b = lines[i + 1].strip()
    if re.fullmatch(r"[A-Z][A-Z0-9_]+", a) and re.fullmatch(r"-?\d+", b) and a not in consts:
        # only accept within the definitions section (first 3000 lines) to avoid picking up enum tables
        if i < 3000:
            consts[a] = int(b)
        i += 2
        continue
    i += 1

# ---- tables ------------------------------------------------------------------------------------
tables = {}
order = []
pat = re.compile(r"^([A-Z][A-Za-z_0-9]*)\s*((?:\[[^\]=]*\]\s*)+)=\s*\{")
i = 0
while i < len(lines):
    m = pat.match(lines[i])
    if not m:
        i += 1
        continue
    name, dims_txt = m.group(1), m.group(2)
    dims = re.findall(r"\[([^\]]*)\]", dims_txt)
    # collect until braces balance
    buf = lines[i][lines[i].index("=") + 1:]
    depth = buf.count("{") - buf.count("}")
    j = i + 1
    while depth > 0 and j < len(lines):
        buf += "\n" + lines[j]
        depth += lines[j].count("{") - lines[j].count("}")
        j += 1
    body = buf[:buf.rfind("}") + 1]
    nums = [int(x) for x in re.findall(r"-?\d+", body)]
    try:
        shape = [int(eval(d, {}, consts)) for d in dims]
    except Exception as e:  # unknown symbol
        print(f"# skip {name}: dims {dims}: {e}", file=sys.stderr)
        i = j
        continue
    total = 1
    for d in shape:
        total *= d
    if total != len(nums):
        print(f"# WARNING {name}: dims {shape} = {total} but {len(nums)} values (line {i+1})", file=sys.stderr)
        i = j
        continue

    def reshape(flat, shp):
        if len(shp) == 1:
            return list(flat)
        step = len(flat) // shp[0]
        return [reshape(flat[k * step:(k + 1) * step], shp[1:]) for k in range(shp[0])]

    if name in tables:
        print(f"# note: {name} defined twice (line {i+1}); keeping the first", file=sys.stderr)
    else:
        tables[name] = (shape, reshape(nums, shape))
        order.append(name)
    i = j

print("# Generated by tools/gen_spec_tables.py from the AV1 specification text. Do not edit.")
print("CONST = {")
for k in sorted(consts):
    print(f"    {k!r}: {consts[k]},")
print("}")
print("globals().update(CONST)")
print()
for name in order:
    shape, val = tables[name]
    print(f"{name} = {val!r}  # dims {shape}")
print(f"\n# {len(consts)} constants, {len(tables)} tables", file=sys.stderr)
