#!/usr/bin/env python3
"""Generate the inverse-transform micro-op ROM from the spec model.

The RTL engine (rtl/itx1d.sv) holds the transform vector T in 64 registers and executes one ROM
row per cycle. A row carries up to NSLOTS independent pair operations (B rotations or H
Hadamards) taken from ONE spec step-line, so there are never dependencies inside a row.
Permutations (DCT bit-reversal, ADST in/out) are separate row kinds handled by the engine's
load/store paths, and ADST4 / identity / WHT are dedicated single-row operations.

We obtain the op sequence by running itx_model with B/H/permute replaced by recorders, so the
ROM is derived from the transcription that the fuzz tests check, not typed in twice.

Usage: tools/gen_itx_ucode.py [NSLOTS] > rtl/itx_ucode.svh
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "tb"))
import itx_model as m  # noqa: E402

_args = [a for a in sys.argv[1:] if not a.startswith("--")]
NSLOTS = int(_args[0]) if _args else 4

# Row kinds
K_NOP, K_OPS, K_PERM_DCT, K_PERM_ADST_IN, K_PERM_ADST_OUT, K_ADST4, K_IDENT, K_WHT, K_END, K_DCT4 = range(10)
OP_NONE, OP_B, OP_H = 0, 1, 2

# Program ids: (n, class) -> program index.  class: 0 DCT, 1 ADST, 2 IDENTITY, 3 WHT
PROGRAMS = [(n, 0) for n in range(2, 7)] + [(n, 1) for n in range(2, 5)] + [(n, 2) for n in range(2, 6)] + [(2, 3)]


def record_program(n, cls):
    """Return a list of rows; each row is (kind, ops) with ops a list of (op, a, b, angle, flip)."""
    lines = []          # list of spec step-lines, each a list of ops
    cur = None
    rows = []

    def new_line():
        nonlocal cur
        cur = []
        lines.append(cur)

    def rec_B(T, a, b, angle, flip, r):
        cur.append((OP_B, a, b, angle & 255, flip))

    def rec_H(T, a, b, flip, r):
        cur.append((OP_H, a, b, 0, flip))

    def rec_perm_dct(T, nn):
        rows.append((K_PERM_DCT, []))

    def rec_perm_in(T, nn):
        rows.append((K_PERM_ADST_IN, []))

    def rec_perm_out(T, nn):
        flush()
        rows.append((K_PERM_ADST_OUT, []))

    def flush():
        # pack each recorded spec line into ceil(len/NSLOTS) rows
        for line in lines:
            for i in range(0, len(line), NSLOTS):
                rows.append((K_OPS, line[i:i + NSLOTS]))
        lines.clear()

    saved = (m.B, m.H, m.inv_dct_permute, m.inv_adst_in_permute, m.inv_adst_out_permute)
    m.B, m.H = rec_B, rec_H
    m.inv_dct_permute, m.inv_adst_in_permute, m.inv_adst_out_permute = rec_perm_dct, rec_perm_in, rec_perm_out
    try:
        T = [0] * (1 << n)
        if cls == 0:
            # Every spec step-line is a python `for` over B/H calls or a single call. We detect line
            # boundaries by wrapping: each B/H call appends to `cur`; a new line begins when the
            # (a) index set would collide with an index already used in the current line.
            used = set()

            def guard(fn):
                def w(T, a, b, *rest):
                    nonlocal used
                    if a in used or b in used:
                        used = set()
                        new_line()
                    used.add(a); used.add(b)
                    fn(T, a, b, *rest)
                return w
            if n == 2:
                rows.append((K_DCT4, []))                      # dedicated single-row op (permute + 2 rotations + 2 Hadamards)
            else:
                m.B, m.H = guard(rec_B), guard(rec_H)
                new_line()
                m.inv_dct(T, n, 24)
                flush()
        elif cls == 1:
            if n == 2:
                rows.append((K_ADST4, []))
            else:
                used = set()

                def guard(fn):
                    def w(T, a, b, *rest):
                        nonlocal used
                        if a in used or b in used:
                            used = set()
                            new_line()
                        used.add(a); used.add(b)
                        fn(T, a, b, *rest)
                    return w
                m.B, m.H = guard(rec_B), guard(rec_H)
                new_line()
                m.inv_adst(T, n, 24)
                flush()
        elif cls == 2:
            rows.append((K_IDENT, []))
        else:
            rows.append((K_WHT, []))
    finally:
        m.B, m.H, m.inv_dct_permute, m.inv_adst_in_permute, m.inv_adst_out_permute = saved
    rows = [r for r in rows if not (r[0] == K_OPS and not r[1])]
    rows.append((K_END, []))
    return rows


def main():
    programs = {}
    for pid, (n, cls) in enumerate(PROGRAMS):
        programs[pid] = record_program(n, cls)
    total = sum(len(r) for r in programs.values())
    out = []
    W = 4 + NSLOTS * 23
    out.append("// Generated by tools/gen_itx_ucode.py — do not edit. NSLOTS=%d" % NSLOTS)
    out.append("// Row: kind[3:0] | slot0..slot%d each {op[1:0], a[5:0], b[5:0], angle[7:0], flip}" % (NSLOTS - 1))
    out.append("// Row kinds: 0 nop, 1 ops, 2 perm_dct, 3 perm_adst_in, 4 perm_adst_out, 5 adst4, 6 identity, 7 wht, 8 end, 9 dct4")
    out.append("// Programs (start row by id): DCT n=2..6 -> 0..4, ADST n=2..4 -> 5..7, IDTX n=2..5 -> 8..11, WHT -> 12")
    out.append("/* verilator lint_off DECLFILENAME */")
    out.append("/* verilator lint_off UNUSEDPARAM */")
    out.append("package itx_ucode_pkg;")
    out.append("  localparam int ITX_NSLOTS = %d;" % NSLOTS)
    out.append("  localparam int ITX_ROWS = %d;" % total)
    out.append("  localparam int ITX_ROW_W = %d;" % W)
    starts = []
    idx = 0
    body = []
    for pid, (n, cls) in enumerate(PROGRAMS):
        starts.append(idx)
        for kind, ops in programs[pid]:
            val = kind
            for s in range(NSLOTS):
                if s < len(ops):
                    op, a, b, ang, flip = ops[s]
                    slot = (op << 21) | (a << 15) | (b << 9) | (ang << 1) | flip
                else:
                    slot = 0
                val |= slot << (4 + s * 23)
            body.append("      8'd%d: row = %d'h%x; // pid %d (n=%d cls=%d) %s" % (
                idx, W, val, pid, n, cls,
                {K_OPS: "ops x%d" % len(ops), K_PERM_DCT: "perm_dct", K_PERM_ADST_IN: "perm_adst_in",
                 K_PERM_ADST_OUT: "perm_adst_out", K_ADST4: "adst4", K_IDENT: "identity", K_WHT: "wht", K_DCT4: "dct4",
                 K_END: "end"}[kind]))
            idx += 1
    out.append("endpackage")
    out.append("")
    out.append("// program id -> first ROM row")
    out.append("module itx_prog_start (input logic [3:0] pid, output logic [7:0] addr);")
    out.append("  always_comb begin")
    out.append("    case (pid)")
    for pid, st in enumerate(starts):
        out.append("      4'd%d: addr = 8'd%d;" % (pid, st))
    out.append("      default: addr = 8'd%d;" % starts[-1])
    out.append("    endcase")
    out.append("  end")
    out.append("endmodule")
    out.append("")
    out.append("module itx_ucode_rom (input logic [7:0] addr, output logic [%d:0] row);" % (W - 1))
    out.append("  always_comb begin")
    out.append("    case (addr)")
    out.extend(body)
    out.append("      default: row = '0;")
    out.append("    endcase")
    out.append("  end")
    out.append("endmodule")
    print("\n".join(out))
    # summary to stderr
    for pid, (n, cls) in enumerate(PROGRAMS):
        rows = programs[pid]
        nops = sum(len(r[1]) for r in rows)
        print(f"pid {pid}: n={n} cls={cls} rows={len(rows)} ops={nops}", file=sys.stderr)


if __name__ == "__main__" and "--check" not in sys.argv:
    main()


# ---- replay check: execute the rows exactly as the RTL engine will --------------------------
def replay(rows, n, cls, vec, r):
    T = list(vec) + [0] * (64 - len(vec))
    N = 1 << n
    for kind, ops in rows:
        if kind == K_PERM_DCT:
            c = list(T)
            for i in range(N):
                T[i] = c[m.brev(n, i)]
        elif kind == K_PERM_ADST_IN:
            c = list(T)
            for i in range(N):
                T[i] = c[(i - 1) if (i & 1) else (N - i - 1)]
        elif kind == K_PERM_ADST_OUT:
            c = list(T)
            for i in range(N):
                a = (i >> 3) & 1
                b = ((i >> 2) & 1) ^ ((i >> 3) & 1)
                cc = ((i >> 1) & 1) ^ ((i >> 2) & 1)
                d = (i & 1) ^ ((i >> 1) & 1)
                idx = ((d << 3) | (cc << 2) | (b << 1) | a) >> (4 - n)
                T[i] = -c[idx] if (i & 1) else c[idx]
        elif kind == K_OPS:
            new = {}
            for op, a, b, ang, flip in ops:       # all reads before any write, like hardware
                if op == OP_B:
                    x = T[a] * m.cos128(ang) - T[b] * m.sin128(ang)
                    y = T[a] * m.sin128(ang) + T[b] * m.cos128(ang)
                    ra, rb = m.round2(x, 12), m.round2(y, 12)
                    if flip:
                        ra, rb = rb, ra
                else:
                    aa, bb = (b, a) if flip else (a, b)
                    lo, hi = -(1 << (r - 1)), (1 << (r - 1)) - 1
                    x, y = T[aa], T[bb]
                    new[aa] = m.clip3(lo, hi, x + y); new[bb] = m.clip3(lo, hi, x - y)
                    continue
                new[a], new[b] = ra, rb
            for k, v in new.items():
                T[k] = v
        elif kind == K_ADST4:
            t4 = T[:4]; m.inv_adst4(t4, r); T[:4] = t4
        elif kind == K_DCT4:
            t4 = T[:4]; m.inv_dct(t4, 2, r); T[:4] = t4
        elif kind == K_IDENT:
            tn = T[:N]; m.inv_identity(tn, n); T[:N] = tn
        elif kind == K_WHT:
            tn = T[:4]; m.inv_wht(tn, 2); T[:4] = tn
    return T[:N]


if __name__ == "__main__" and "--check" in sys.argv:
    import random
    rng = random.Random(11)
    bad = 0
    for pid, (n, cls) in enumerate(PROGRAMS):
        rows = record_program(n, cls)
        N = 1 << n
        for _ in range(300):
            vec = [rng.randint(-3000, 3000) for _ in range(N)]
            ref = list(vec)
            try:
                if cls == 0: m.inv_dct(ref, n, 24)
                elif cls == 1: m.inv_adst(ref, n, 24)
                elif cls == 2: m.inv_identity(ref, n)
                else: m.inv_wht(ref, 2)
            except m.Nonconformant:
                continue
            got = replay(rows, n, cls, vec, 24)
            if got != ref:
                bad += 1
                if bad < 4:
                    print(f"MISMATCH pid {pid} n={n} cls={cls}\n vec={vec}\n ref={ref}\n got={got}", file=sys.stderr)
    print("replay check:", "OK" if bad == 0 else f"{bad} mismatches", file=sys.stderr)
    sys.exit(1 if bad else 0)
