#!/usr/bin/env python3
"""Emit rtl/cdf_map_pkg.sv from tb/cdf_map.py (base address, dims/strides and alphabet size per table)."""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tb"))
import cdf_map as M     # noqa: E402


def main():
    out = ["// Generated by tools/gen_cdf_map.py from tb/cdf_map.py -- do not edit.",
           "// One 246-bit row per CDF: [239:0] 15 x 16-bit inverted CDF entries, [245:240] adaptation counter.",
           "package cdf_map_pkg;",
           f"  localparam int CDF_ROWS = {M.ROWS};",
           f"  localparam int CDF_COEF_ROWS = {M.COEF_ROWS};   // rows [0, CDF_COEF_ROWS) depend on base_q_idx",
           f"  localparam int CDF_AW = {max(1, (M.ROWS - 1).bit_length())};",
           ""]
    for name in M.INTRA_TABLES:
        e = M.MAP[name]
        u = name.upper()
        out.append(f"  localparam int CDF_{u} = {e['base']};   // dims {e['dims']} N={e['N']}")
        out.append(f"  localparam int CDF_{u}_N = {e['N']};")
        # strides for each dim (row-major): stride_i = prod(dims[i+1:])
        for i in range(len(e["dims"])):
            s = 1
            for x in e["dims"][i + 1:]:
                s *= x
            out.append(f"  localparam int CDF_{u}_S{i} = {s};")
    out.append("endpackage")
    (ROOT / "rtl" / "cdf_map_pkg.sv").write_text("\n".join(out) + "\n")
    print(f"rtl/cdf_map_pkg.sv: {M.ROWS} rows")


if __name__ == "__main__":
    main()
