#!/usr/bin/env python3
"""Emit rtl/scan_rom.sv: the Default (zig-zag) scan tables for every adjusted transform size as one ROM,
plus rtl/tx_tables_pkg.sv with the small transform-size tables and Coeff_Base_Ctx_Offset as functions.
Mrow/Mcol scans are arithmetic (row-major / column-major; asserted here against the spec tables).
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tb"))
import av1_tables as T      # noqa: E402

TXNAMES = ["TX_4X4", "TX_8X8", "TX_16X16", "TX_32X32", "TX_64X64", "TX_4X8", "TX_8X4", "TX_8X16", "TX_16X8",
           "TX_16X32", "TX_32X16", "TX_32X64", "TX_64X32", "TX_4X16", "TX_16X4", "TX_8X32", "TX_32X8",
           "TX_16X64", "TX_64X16"]


def main():
    # scan ROM: concatenate Default_Scan_WxH for each adjusted size (in tx enum order), record bases
    entries = []
    base = {}
    for tx in range(19):
        adj = T.Adjusted_Tx_Size[tx]
        if adj != tx:
            continue
        w, h = T.Tx_Width[tx], T.Tx_Height[tx]
        tab = getattr(T, f"Default_Scan_{w}x{h}")
        assert len(tab) == w * h
        base[tx] = len(entries)
        entries += tab
        if w <= 16 and h <= 16:
            assert getattr(T, f"Mrow_Scan_{w}x{h}") == list(range(w * h))
            assert getattr(T, f"Mcol_Scan_{w}x{h}") == [(c % h) * w + c // h for c in range(w * h)]
    n = len(entries)
    aw = (n - 1).bit_length()
    sv = ["// Generated by tools/gen_scan_rom.py from the spec's Default_Scan_* tables -- do not edit.",
          "// pos = Default_Scan_<adjusted size>[c]; 1-cycle registered read. Mrow/Mcol scans are arithmetic",
          "// (see tx_tables_pkg::scan_pos).",
          "module scan_rom (",
          "    input  logic        clk,",
          f"    input  logic [{aw - 1}:0] addr,",
          "    output logic [9:0]  data",
          ");",
          f"  logic [9:0] rom [0:{n - 1}];",
          "  initial begin"]
    for i, v in enumerate(entries):
        sv.append(f"    rom[{i}] = 10'd{v};")
    sv += ["  end",
           "  always_ff @(posedge clk) data <= rom[addr];",
           "endmodule"]
    (ROOT / "rtl" / "scan_rom.sv").write_text("\n".join(sv) + "\n")

    pk = ["// Generated by tools/gen_scan_rom.py -- do not edit.",
          "package tx_tables_pkg;",
          f"  localparam int SCAN_ROM_AW = {aw};",
          f"  localparam int SCAN_ROM_ENTRIES = {n};"]

    def fn(name, width, vals, comment=""):
        pk.append(f"  function automatic logic [{width - 1}:0] {name}(input logic [4:0] tx);  {comment}")
        pk.append("    case (tx)")
        for i, v in enumerate(vals):
            pk.append(f"      5'd{i}: {name} = {width}'d{v};")
        pk.append(f"      default: {name} = {width}'d0;")
        pk.append("    endcase")
        pk.append("  endfunction")
    fn("tx_w_log2", 3, T.Tx_Width_Log2, "// Tx_Width_Log2")
    fn("tx_h_log2", 3, T.Tx_Height_Log2, "// Tx_Height_Log2")
    fn("tx_sqr", 3, T.Tx_Size_Sqr, "// Tx_Size_Sqr")
    fn("tx_sqr_up", 3, T.Tx_Size_Sqr_Up, "// Tx_Size_Sqr_Up")
    fn("tx_adj", 5, T.Adjusted_Tx_Size, "// Adjusted_Tx_Size")
    fn("scan_base", aw, [base.get(T.Adjusted_Tx_Size[tx], 0) for tx in range(19)], "// scan ROM base of Adjusted_Tx_Size[tx]")
    # Coeff_Base_Ctx_Offset[txSz][min(row,4)][min(col,4)]
    pk.append("  function automatic logic [5:0] coeff_base_ctx_offset(input logic [4:0] tx, input logic [2:0] r, input logic [2:0] c);")
    pk.append("    case ({tx, r, c})")
    for tx in range(19):
        for r in range(5):
            for c in range(5):
                pk.append(f"      {{5'd{tx}, 3'd{r}, 3'd{c}}}: coeff_base_ctx_offset = 6'd{T.Coeff_Base_Ctx_Offset[tx][r][c]};")
    pk.append("      default: coeff_base_ctx_offset = 6'd0;")
    pk.append("    endcase")
    pk.append("  endfunction")
    pk.append("endpackage")
    (ROOT / "rtl" / "tx_tables_pkg.sv").write_text("\n".join(pk) + "\n")
    print(f"rtl/scan_rom.sv: {n} entries ({aw}-bit address); rtl/tx_tables_pkg.sv written")


if __name__ == "__main__":
    main()
