#!/usr/bin/env python3
"""Emit rtl/blk_tables_pkg.sv: block-size / mode / transform-set lookup tables from the spec (tb/av1_tables.py)
as SystemVerilog functions, for the block-level syntax RTL."""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tb"))
import av1_tables as T      # noqa: E402

out = ["// Generated by tools/gen_blk_tables.py from the spec tables -- do not edit.", "package blk_tables_pkg;"]


def fn1(name, width, vals, in_w, comment):
    out.append(f"  function automatic logic [{width - 1}:0] {name}(input logic [{in_w - 1}:0] i);  // {comment}")
    out.append("    case (i)")
    for k, v in enumerate(vals):
        out.append(f"      {in_w}'d{k}: {name} = {width}'d{v};")
    out.append(f"      default: {name} = {width}'d0;")
    out.append("    endcase")
    out.append("  endfunction")


fn1("num4x4w", 6, T.Num_4x4_Blocks_Wide, 5, "Num_4x4_Blocks_Wide[bsize]")
fn1("num4x4h", 6, T.Num_4x4_Blocks_High, 5, "Num_4x4_Blocks_High[bsize]")
fn1("blk_w", 8, T.Block_Width, 5, "Block_Width[bsize]")
fn1("blk_h", 8, T.Block_Height, 5, "Block_Height[bsize]")
fn1("mi_w_log2", 3, T.Mi_Width_Log2, 5, "Mi_Width_Log2[bsize]")
fn1("mi_h_log2", 3, T.Mi_Height_Log2, 5, "Mi_Height_Log2[bsize]")
fn1("intra_mode_ctx", 3, T.Intra_Mode_Context, 4, "Intra_Mode_Context[ymode]")
fn1("max_tx_size_rect", 5, T.Max_Tx_Size_Rect, 5, "Max_Tx_Size_Rect[bsize]")
fn1("max_tx_depth", 3, T.Max_Tx_Depth, 5, "Max_Tx_Depth[bsize]")
fn1("split_tx_size", 5, T.Split_Tx_Size, 5, "Split_Tx_Size[tx]")
fn1("tx_width", 7, T.Tx_Width, 5, "Tx_Width[tx]")
fn1("tx_height", 7, T.Tx_Height, 5, "Tx_Height[tx]")
fn1("mode_to_txfm", 4, T.Mode_To_Txfm, 4, "Mode_To_Txfm[mode] (intra modes incl. UV_CFL)")
fn1("tx_type_intra_inv_set1", 4, T.Tx_Type_Intra_Inv_Set1, 3, "Tx_Type_Intra_Inv_Set1[v]")
fn1("tx_type_intra_inv_set2", 4, T.Tx_Type_Intra_Inv_Set2, 3, "Tx_Type_Intra_Inv_Set2[v]")
fn1("filter_intra_mode_to_intra_dir", 4, T.Filter_Intra_Mode_To_Intra_Dir, 3, "Filter_Intra_Mode_To_Intra_Dir[m]")
fn1("tx_type_inter_inv_set1", 4, T.Tx_Type_Inter_Inv_Set1, 4, "Tx_Type_Inter_Inv_Set1[v]")
fn1("tx_type_inter_inv_set2", 4, T.Tx_Type_Inter_Inv_Set2, 4, "Tx_Type_Inter_Inv_Set2[v]")
fn1("tx_type_inter_inv_set3", 4, T.Tx_Type_Inter_Inv_Set3, 1, "Tx_Type_Inter_Inv_Set3[v]")
fn1("sb_size_bsize", 5, [T.ENUM["BLOCK_64X64"], T.ENUM["BLOCK_128X128"]], 1, "superblock block size by use_128x128")

# 2D: Partition_Subsize[partition][bsize]
out.append("  function automatic logic [4:0] partition_subsize(input logic [3:0] p, input logic [4:0] b);  // Partition_Subsize[p][b]")
out.append("    case ({p, b})")
for p in range(10):
    for b in range(22):
        out.append(f"      {{4'd{p}, 5'd{b}}}: partition_subsize = 5'd{T.Partition_Subsize[p][b]};")
out.append("      default: partition_subsize = 5'd22;")
out.append("    endcase")
out.append("  endfunction")
# Subsampled_Size[bsize][ssx][ssy]
out.append("  function automatic logic [4:0] subsampled_size(input logic [4:0] b, input logic sx, input logic sy);  // Subsampled_Size[b][sx][sy]")
out.append("    case ({b, sx, sy})")
for b in range(22):
    for sx in range(2):
        for sy in range(2):
            out.append(f"      {{5'd{b}, 1'b{sx}, 1'b{sy}}}: subsampled_size = 5'd{T.Subsampled_Size[b][sx][sy]};")
out.append("      default: subsampled_size = 5'd22;")
out.append("    endcase")
out.append("  endfunction")
# Tx_Type_In_Set_Intra[set][type]
out.append("  function automatic logic tx_type_in_set_inter(input logic [1:0] s, input logic [3:0] t);  // Tx_Type_In_Set_Inter[s][t]")
out.append("    case ({s, t})")
for s_ in range(4):
    for t in range(16):
        out.append(f"      {{2'd{s_}, 4'd{t}}}: tx_type_in_set_inter = 1'b{T.Tx_Type_In_Set_Inter[s_][t]};")
out.append("      default: tx_type_in_set_inter = 1'b0;")
out.append("    endcase")
out.append("  endfunction")
out.append("  function automatic logic tx_type_in_set_intra(input logic [1:0] s, input logic [3:0] t);  // Tx_Type_In_Set_Intra[s][t]")
out.append("    case ({s, t})")
for s in range(3):
    for t in range(16):
        out.append(f"      {{2'd{s}, 4'd{t}}}: tx_type_in_set_intra = 1'b{T.Tx_Type_In_Set_Intra[s][t]};")
out.append("      default: tx_type_in_set_intra = 1'b0;")
out.append("    endcase")
out.append("  endfunction")
out.append("  localparam logic [4:0] BLOCK_INVALID = 5'd22;")
out.append("endpackage")
(ROOT / "rtl" / "blk_tables_pkg.sv").write_text("\n".join(out) + "\n")
print("rtl/blk_tables_pkg.sv written")
