#!/usr/bin/env python3
"""Emit the dequantisation tables for the reconstruction RTL (spec 7.12.2 / 7.12.3):
  rtl/q_tables_pkg.sv : dc_qlookup(bdidx, q) / ac_qlookup(bdidx, q) (Dc_Qlookup / Ac_Qlookup, 3 x 256 x 15 b),
                        qm_offset(txsz) (Qm_Offset)
  rtl/qm_rom.hex      : Quantizer_Matrix[15][2][3344] flattened as level*6688 + plane*3344 + idx, one byte per line
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tb"))
import av1_tables as T      # noqa: E402

out = ["// Generated by tools/gen_q_tables.py from the spec tables -- do not edit.", "package q_tables_pkg;"]


def fn2(name, width, tab, comment):
    out.append(f"  function automatic logic [{width - 1}:0] {name}(input logic [1:0] b, input logic [7:0] q);  // {comment}")
    out.append("    case ({b, q})")
    for b in range(3):
        for q in range(256):
            out.append(f"      10'd{(b << 8) | q}: {name} = {width}'d{tab[b][q]};")
    out.append(f"      default: {name} = {width}'d0;")
    out.append("    endcase")
    out.append("  endfunction")


fn2("dc_qlookup", 15, T.Dc_Qlookup, "Dc_Qlookup[(BitDepth-8)>>1][qindex]")
fn2("ac_qlookup", 15, T.Ac_Qlookup, "Ac_Qlookup[(BitDepth-8)>>1][qindex]")
out.append("  function automatic logic [11:0] qm_offset(input logic [4:0] tx);  // Qm_Offset[txSz]")
out.append("    case (tx)")
for k, v in enumerate(T.Qm_Offset):
    out.append(f"      5'd{k}: qm_offset = 12'd{v};")
out.append("      default: qm_offset = 12'd0;")
out.append("    endcase")
out.append("  endfunction")
out.append("  localparam int QM_LEVEL_STRIDE = 6688;   // 2 planes x 3344")
out.append("  localparam int QM_PLANE_STRIDE = 3344;")
out.append("  localparam int QM_ROM_SIZE = 100320;     // 15 x 2 x 3344")
out.append("endpackage")
(ROOT / "rtl" / "q_tables_pkg.sv").write_text("\n".join(out) + "\n")

lines = []
for level in range(15):
    for plane in range(2):
        row = T.Quantizer_Matrix[level][plane]
        assert len(row) == 3344
        lines.extend(f"{v:02x}" for v in row)
assert len(lines) == 100320
(ROOT / "rtl" / "qm_rom.hex").write_text("\n".join(lines) + "\n")
print("q_tables_pkg.sv + qm_rom.hex written")
