"""CDF row address map shared by the RTL (rtl/cdf_map_pkg.sv, generated by tools/gen_cdf_map.py) and the
testbenches. One row per CDF (all context indices flattened row-major); a row is 15 x 16-bit *inverted*
CDF entries (32768 - cdf[k], k < N-1, entry N-1 = 0, unused entries 0) at bits [16k +: 16] and the 6-bit
adaptation counter at [245:240] -- exactly msac's req_cdf/req_cnt.

Only the tables an intra frame can use are mapped (inter tables are not stored).
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import av1_tables as T      # noqa: E402
import tile_model as tm     # noqa: E402

ROW_BITS = 246
# coefficient tables come first: their defaults depend on base_q_idx (4 variants)
COEF_TABLES = ["Txb_Skip", "Eob_Pt_16", "Eob_Pt_32", "Eob_Pt_64", "Eob_Pt_128", "Eob_Pt_256", "Eob_Pt_512",
               "Eob_Pt_1024", "Eob_Extra", "Dc_Sign", "Coeff_Base_Eob", "Coeff_Base", "Coeff_Br"]
INTRA_TABLES = COEF_TABLES + [
    "Partition_W8", "Partition_W16", "Partition_W32", "Partition_W64", "Partition_W128",
    "Intrabc", "Intra_Frame_Y_Mode", "Uv_Mode_Cfl_Allowed", "Uv_Mode_Cfl_Not_Allowed",
    "Segment_Id", "Segment_Id_Predicted", "Skip", "Delta_Q", "Delta_Lf", "Delta_Lf_Multi",
    "Angle_Delta", "Cfl_Sign", "Cfl_Alpha",
    "Palette_Y_Mode", "Palette_Y_Size", "Palette_Uv_Mode", "Palette_Uv_Size"] + \
    ["Palette_Size_%d_%s_Color" % (n, p) for n in range(2, 9) for p in ("Y", "Uv")] + [
    "Filter_Intra", "Filter_Intra_Mode", "Tx_8x8", "Tx_16x16", "Tx_32x32", "Tx_64x64",
    "Intra_Tx_Type_Set1", "Intra_Tx_Type_Set2", "Use_Wiener", "Use_Sgrproj", "Restoration_Type",
    # intra block copy (inter-style syntax inside intra frames): var-tx split, inter tx types, MV coding
    "Txfm_Split", "Inter_Tx_Type_Set1", "Inter_Tx_Type_Set2", "Inter_Tx_Type_Set3",
    "Mv_Joint", "Mv_Class", "Mv_Class0_Bit", "Mv_Class0_Fr", "Mv_Class0_Hp", "Mv_Sign", "Mv_Bit", "Mv_Fr", "Mv_Hp"]


def _shape(v):
    dims = []
    while isinstance(v, list) and v and isinstance(v[0], list):
        dims.append(len(v))
        v = v[0]
    return dims, len(v) - 1


def build_map():
    d = tm.make_cdfs(0)
    m = {}
    base = 0
    for name in INTRA_TABLES:
        dims, N = _shape(d[name])
        rows = 1
        for x in dims:
            rows *= x
        m[name] = dict(base=base, dims=dims, N=N, rows=rows)
        base += rows
    return m, base


MAP, ROWS = build_map()
COEF_ROWS = sum(MAP[n]["rows"] for n in COEF_TABLES)


def addr(name, *idx):
    e = MAP[name]
    assert len(idx) == len(e["dims"]), (name, idx, e["dims"])
    a = 0
    for i, n in zip(idx, e["dims"]):
        assert 0 <= i < n, (name, idx)
        a = a * n + i
    return e["base"] + a


def pack_row(cdf):
    """cdf in spec form [cdf0..cdf(N-2), 32768, counter] -> 246-bit row int."""
    N = len(cdf) - 1
    v = 0
    for k in range(N - 1):
        v |= ((32768 - cdf[k]) & 0xFFFF) << (16 * k)
    v |= (cdf[N] & 0x3F) << 240
    return v


def unpack_row(v, N):
    """246-bit row -> spec-form cdf list (for comparing RTL state with the model)."""
    cdf = [32768 - ((v >> (16 * k)) & 0xFFFF) for k in range(N - 1)] + [32768, (v >> 240) & 0x3F]
    return cdf


def default_rows(base_q_idx):
    """The whole store's default contents for a tile of a frame with this base_q_idx: list of ROWS ints."""
    d = tm.make_cdfs(base_q_idx)
    out = [0] * ROWS
    for name in INTRA_TABLES:
        e = MAP[name]

        def flat(v, depth):
            if depth == len(e["dims"]):
                yield v
            else:
                for sub in v:
                    yield from flat(sub, depth + 1)
        for i, row in enumerate(flat(d[name], 0)):
            out[e["base"] + i] = pack_row(row)
    return out


if __name__ == "__main__":
    print(f"{ROWS} rows ({COEF_ROWS} coefficient rows), {ROWS * ROW_BITS / 8 / 1024:.1f} KiB")
    for n in INTRA_TABLES:
        e = MAP[n]
        print(f"  {n:24s} base {e['base']:5d} dims {e['dims']} N {e['N']}")
